/*
Copyright 2023 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	nodepoolv1 "github.com/cilium/cilium/pkg/gke/apis/nodepool/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// FakeNodePoolLists implements NodePoolListInterface
type FakeNodePoolLists struct {
	Fake *FakeBaremetalV1
	ns   string
}

var nodepoollistsResource = schema.GroupVersionResource{Group: "baremetal.cluster.gke.io", Version: "v1", Resource: "nodepoollists"}

var nodepoollistsKind = schema.GroupVersionKind{Group: "baremetal.cluster.gke.io", Version: "v1", Kind: "NodePoolList"}

// Get takes name of the nodePoolList, and returns the corresponding nodePoolList object, and an error if there is any.
func (c *FakeNodePoolLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *nodepoolv1.NodePoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodepoollistsResource, c.ns, name), &nodepoolv1.NodePoolList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nodepoolv1.NodePoolList), err
}
