/*
Copyright 2023 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	remotenodev1alpha1 "github.com/cilium/cilium/pkg/gke/apis/remotenode/v1alpha1"
	versioned "github.com/cilium/cilium/pkg/gke/client/remotenode/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/gke/client/remotenode/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/cilium/cilium/pkg/gke/client/remotenode/listers/remotenode/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RemoteNodeInformer provides access to a shared informer and lister for
// RemoteNodes.
type RemoteNodeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RemoteNodeLister
}

type remoteNodeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRemoteNodeInformer constructs a new informer for RemoteNode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRemoteNodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRemoteNodeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRemoteNodeInformer constructs a new informer for RemoteNode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRemoteNodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1alpha1().RemoteNodes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1alpha1().RemoteNodes(namespace).Watch(context.TODO(), options)
			},
		},
		&remotenodev1alpha1.RemoteNode{},
		resyncPeriod,
		indexers,
	)
}

func (f *remoteNodeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRemoteNodeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *remoteNodeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&remotenodev1alpha1.RemoteNode{}, f.defaultInformer)
}

func (f *remoteNodeInformer) Lister() v1alpha1.RemoteNodeLister {
	return v1alpha1.NewRemoteNodeLister(f.Informer().GetIndexer())
}
