/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/gke/apis/redirectservice/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRedirectServices implements RedirectServiceInterface
type FakeRedirectServices struct {
	Fake *FakeNetworkingV1alpha1
	ns   string
}

var redirectservicesResource = schema.GroupVersionResource{Group: "networking.gke.io", Version: "v1alpha1", Resource: "redirectservices"}

var redirectservicesKind = schema.GroupVersionKind{Group: "networking.gke.io", Version: "v1alpha1", Kind: "RedirectService"}

// Get takes name of the redirectService, and returns the corresponding redirectService object, and an error if there is any.
func (c *FakeRedirectServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RedirectService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(redirectservicesResource, c.ns, name), &v1alpha1.RedirectService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedirectService), err
}

// List takes label and field selectors, and returns the list of RedirectServices that match those selectors.
func (c *FakeRedirectServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RedirectServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(redirectservicesResource, redirectservicesKind, c.ns, opts), &v1alpha1.RedirectServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RedirectServiceList{ListMeta: obj.(*v1alpha1.RedirectServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.RedirectServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested redirectServices.
func (c *FakeRedirectServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(redirectservicesResource, c.ns, opts))

}

// Create takes the representation of a redirectService and creates it.  Returns the server's representation of the redirectService, and an error, if there is any.
func (c *FakeRedirectServices) Create(ctx context.Context, redirectService *v1alpha1.RedirectService, opts v1.CreateOptions) (result *v1alpha1.RedirectService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(redirectservicesResource, c.ns, redirectService), &v1alpha1.RedirectService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedirectService), err
}

// Update takes the representation of a redirectService and updates it. Returns the server's representation of the redirectService, and an error, if there is any.
func (c *FakeRedirectServices) Update(ctx context.Context, redirectService *v1alpha1.RedirectService, opts v1.UpdateOptions) (result *v1alpha1.RedirectService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(redirectservicesResource, c.ns, redirectService), &v1alpha1.RedirectService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedirectService), err
}

// Delete takes name of the redirectService and deletes it. Returns an error if one occurs.
func (c *FakeRedirectServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(redirectservicesResource, c.ns, name), &v1alpha1.RedirectService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRedirectServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(redirectservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RedirectServiceList{})
	return err
}

// Patch applies the patch and returns the patched redirectService.
func (c *FakeRedirectServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RedirectService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(redirectservicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.RedirectService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedirectService), err
}
