/*
Copyright 2022 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/gke/apis/fqdnnetworkpolicy/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/gke/client/fqdnnetworkpolicy/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	rest "k8s.io/client-go/rest"
)

// FQDNNetworkPolicyListsGetter has a method to return a FQDNNetworkPolicyListInterface.
// A group's client should implement this interface.
type FQDNNetworkPolicyListsGetter interface {
	FQDNNetworkPolicyLists(namespace string) FQDNNetworkPolicyListInterface
}

// FQDNNetworkPolicyListInterface has methods to work with FQDNNetworkPolicyList resources.
type FQDNNetworkPolicyListInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FQDNNetworkPolicyList, error)
	FQDNNetworkPolicyListExpansion
}

// fQDNNetworkPolicyLists implements FQDNNetworkPolicyListInterface
type fQDNNetworkPolicyLists struct {
	client rest.Interface
	ns     string
}

// newFQDNNetworkPolicyLists returns a FQDNNetworkPolicyLists
func newFQDNNetworkPolicyLists(c *NetworkingV1alpha1Client, namespace string) *fQDNNetworkPolicyLists {
	return &fQDNNetworkPolicyLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fQDNNetworkPolicyList, and returns the corresponding fQDNNetworkPolicyList object, and an error if there is any.
func (c *fQDNNetworkPolicyLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FQDNNetworkPolicyList, err error) {
	result = &v1alpha1.FQDNNetworkPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fqdnnetworkpolicylists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}
