/*
Copyright 2022 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/gke/apis/fqdnnetworkpolicy/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/gke/client/fqdnnetworkpolicy/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FQDNNetworkPoliciesGetter has a method to return a FQDNNetworkPolicyInterface.
// A group's client should implement this interface.
type FQDNNetworkPoliciesGetter interface {
	FQDNNetworkPolicies(namespace string) FQDNNetworkPolicyInterface
}

// FQDNNetworkPolicyInterface has methods to work with FQDNNetworkPolicy resources.
type FQDNNetworkPolicyInterface interface {
	Create(ctx context.Context, fQDNNetworkPolicy *v1alpha1.FQDNNetworkPolicy, opts v1.CreateOptions) (*v1alpha1.FQDNNetworkPolicy, error)
	Update(ctx context.Context, fQDNNetworkPolicy *v1alpha1.FQDNNetworkPolicy, opts v1.UpdateOptions) (*v1alpha1.FQDNNetworkPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FQDNNetworkPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.FQDNNetworkPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FQDNNetworkPolicy, err error)
	FQDNNetworkPolicyExpansion
}

// fQDNNetworkPolicies implements FQDNNetworkPolicyInterface
type fQDNNetworkPolicies struct {
	client rest.Interface
	ns     string
}

// newFQDNNetworkPolicies returns a FQDNNetworkPolicies
func newFQDNNetworkPolicies(c *NetworkingV1alpha1Client, namespace string) *fQDNNetworkPolicies {
	return &fQDNNetworkPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fQDNNetworkPolicy, and returns the corresponding fQDNNetworkPolicy object, and an error if there is any.
func (c *fQDNNetworkPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FQDNNetworkPolicy, err error) {
	result = &v1alpha1.FQDNNetworkPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fqdnnetworkpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FQDNNetworkPolicies that match those selectors.
func (c *fQDNNetworkPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FQDNNetworkPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.FQDNNetworkPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fqdnnetworkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fQDNNetworkPolicies.
func (c *fQDNNetworkPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("fqdnnetworkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a fQDNNetworkPolicy and creates it.  Returns the server's representation of the fQDNNetworkPolicy, and an error, if there is any.
func (c *fQDNNetworkPolicies) Create(ctx context.Context, fQDNNetworkPolicy *v1alpha1.FQDNNetworkPolicy, opts v1.CreateOptions) (result *v1alpha1.FQDNNetworkPolicy, err error) {
	result = &v1alpha1.FQDNNetworkPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("fqdnnetworkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fQDNNetworkPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a fQDNNetworkPolicy and updates it. Returns the server's representation of the fQDNNetworkPolicy, and an error, if there is any.
func (c *fQDNNetworkPolicies) Update(ctx context.Context, fQDNNetworkPolicy *v1alpha1.FQDNNetworkPolicy, opts v1.UpdateOptions) (result *v1alpha1.FQDNNetworkPolicy, err error) {
	result = &v1alpha1.FQDNNetworkPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fqdnnetworkpolicies").
		Name(fQDNNetworkPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fQDNNetworkPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the fQDNNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *fQDNNetworkPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fqdnnetworkpolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fQDNNetworkPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fqdnnetworkpolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched fQDNNetworkPolicy.
func (c *fQDNNetworkPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FQDNNetworkPolicy, err error) {
	result = &v1alpha1.FQDNNetworkPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("fqdnnetworkpolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
