// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFlowTaggers implements FlowTaggerInterface
type FakeFlowTaggers struct {
	Fake *FakeCiliumV2alpha1
}

var flowtaggersResource = v2alpha1.SchemeGroupVersion.WithResource("flowtaggers")

var flowtaggersKind = v2alpha1.SchemeGroupVersion.WithKind("FlowTagger")

// Get takes name of the flowTagger, and returns the corresponding flowTagger object, and an error if there is any.
func (c *FakeFlowTaggers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.FlowTagger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(flowtaggersResource, name), &v2alpha1.FlowTagger{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.FlowTagger), err
}

// List takes label and field selectors, and returns the list of FlowTaggers that match those selectors.
func (c *FakeFlowTaggers) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.FlowTaggerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(flowtaggersResource, flowtaggersKind, opts), &v2alpha1.FlowTaggerList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.FlowTaggerList{ListMeta: obj.(*v2alpha1.FlowTaggerList).ListMeta}
	for _, item := range obj.(*v2alpha1.FlowTaggerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested flowTaggers.
func (c *FakeFlowTaggers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(flowtaggersResource, opts))
}

// Create takes the representation of a flowTagger and creates it.  Returns the server's representation of the flowTagger, and an error, if there is any.
func (c *FakeFlowTaggers) Create(ctx context.Context, flowTagger *v2alpha1.FlowTagger, opts v1.CreateOptions) (result *v2alpha1.FlowTagger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(flowtaggersResource, flowTagger), &v2alpha1.FlowTagger{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.FlowTagger), err
}

// Update takes the representation of a flowTagger and updates it. Returns the server's representation of the flowTagger, and an error, if there is any.
func (c *FakeFlowTaggers) Update(ctx context.Context, flowTagger *v2alpha1.FlowTagger, opts v1.UpdateOptions) (result *v2alpha1.FlowTagger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(flowtaggersResource, flowTagger), &v2alpha1.FlowTagger{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.FlowTagger), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFlowTaggers) UpdateStatus(ctx context.Context, flowTagger *v2alpha1.FlowTagger, opts v1.UpdateOptions) (*v2alpha1.FlowTagger, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(flowtaggersResource, "status", flowTagger), &v2alpha1.FlowTagger{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.FlowTagger), err
}

// Delete takes name of the flowTagger and deletes it. Returns an error if one occurs.
func (c *FakeFlowTaggers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(flowtaggersResource, name, opts), &v2alpha1.FlowTagger{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFlowTaggers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(flowtaggersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.FlowTaggerList{})
	return err
}

// Patch applies the patch and returns the patched flowTagger.
func (c *FakeFlowTaggers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.FlowTagger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(flowtaggersResource, name, pt, data, subresources...), &v2alpha1.FlowTagger{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.FlowTagger), err
}
