presubmits:
- name: gke-advanced-datapath-presubmit-unit
  always_run: true
  decorate: true
  decoration_config:
    timeout: 120m
  labels:
    preset-cookie-file: "true"
    preset-cookie-file-env: "true"
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    prow.k8s.io/gerrit-report-label: Unit-Verified
  path_alias: gke-internal.googlesource.com/third_party/cilium
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20230124-0f88b78d2-go-canary
      env:
      - name: GCP_PROJECT
        value: gke-anthos-datapath-presubmits
      command:
      - runner.sh
      - ./google_test/presubmit-unit.sh
- name: gke-advanced-datapath-presubmit-upstream-k8s-conformance
  trigger: /test upstream-k8s-conformance
  rerun_command: /test upstream-k8s-conformance
  always_run: true
  decorate: true
  decoration_config:
    timeout: 240m
  labels:
    preset-cookie-file: "true"
    preset-cookie-file-env: "true"
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-k8s-ssh: "true"
    prow.k8s.io/gerrit-report-label: "Verified"
  path_alias: gke-internal.googlesource.com/third_party/cilium
  spec:
    containers:
    - image: gcr.io/tailorbird/kubetest2-tailorbird:latest
      securityContext:
        # needed for docker-in-docker
        privileged: true
      env:
      - name: GCP_PROJECT
        value: anthos-networking-ci
      - name: TEST_TYPE
        value: conformance
      command:
      - runner.sh
      args:
      - ./google_test/upstream_test/run_e2e_tailorbird_with_kind_cluster.sh
- name: gke-advanced-datapath-presubmit-upstream-connectivity
  trigger: /test upstream-connectivity
  rerun_command: /test upstream-connectivity
  always_run: true
  decorate: true
  decoration_config:
    timeout: 240m
  labels:
    preset-cookie-file: "true"
    preset-cookie-file-env: "true"
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-k8s-ssh: "true"
  path_alias: gke-internal.googlesource.com/third_party/cilium
  spec:
    containers:
    - image: gcr.io/tailorbird/kubetest2-tailorbird:latest
      securityContext:
        # needed for docker-in-docker
        privileged: true
      env:
      - name: GCP_PROJECT
        value: anthos-networking-ci
      - name: TEST_TYPE
        value: connectivity
      command:
      - runner.sh
      args:
      - ./google_test/upstream_test/run_e2e_tailorbird_with_kind_cluster.sh
