presubmits:
- name: gke-advanced-datapath-presubmit-unit
  cluster: anthos-networking-ci-us-west1-b
  trigger: /test gke-advanced-datapath-presubmit-unit$
  rerun_command: /test gke-advanced-datapath-presubmit-unit
  always_run: true
  skip_fetch_head: true
  decorate: true
  decoration_config:
    gcs_configuration:
      bucket: "anthos-networking-ci"
      path_strategy: "explicit"
    timeout: 120m
  labels:
    preset-cookie-file: "true"
    preset-cookie-file-env: "true"
    prow.k8s.io/gerrit-report-label: Unit-Verified
    prow.k8s.io/pubsub.project: "anthos-networking-ci"
    prow.k8s.io/pubsub.runID: "prow-etl-presubmit-tests"
    prow.k8s.io/pubsub.topic: "prow-etl-trigger"
  path_alias: gke-internal.googlesource.com/third_party/cilium
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20230124-0f88b78d2-go-canary
      env:
      - name: USER
        value: prow
      - name: GCP_PROJECT
        value: gke-anthos-datapath-presubmits
      command:
      - runner.sh
      - ./google_test/presubmit-unit.sh
- name: gke-advanced-datapath-presubmit-upstream-k8s-conformance
  cluster: anthos-networking-ci-us-west1-b
  trigger: /test upstream-k8s-conformance$
  rerun_command: /test upstream-k8s-conformance
  always_run: true
  skip_fetch_head: true
  decorate: true
  decoration_config:
    gcs_configuration:
      bucket: "anthos-networking-ci"
      path_strategy: "explicit"
    timeout: 240m
  labels:
    preset-cookie-file: "true"
    preset-cookie-file-env: "true"
    preset-dind-enabled: "true"
    prow.k8s.io/gerrit-report-label: "Verified"
    prow.k8s.io/pubsub.project: "anthos-networking-ci"
    prow.k8s.io/pubsub.topic: "prow-etl-trigger"
    prow.k8s.io/pubsub.runID: "prow-etl-presubmit-tests"
  path_alias: gke-internal.googlesource.com/third_party/cilium
  spec:
    containers:
    - image: gcr.io/tailorbird/kubetest2-tailorbird@sha256:dd6edb7b068410208ae185e780bfef1629ea5e07ce566c17132edb1070a71d0d
      securityContext:
        # needed for docker-in-docker
        privileged: true
      env:
      - name: GCP_PROJECT
        value: anthos-networking-ci
      - name: TEST_TYPE
        value: conformance
      command:
      - runner.sh
      args:
      - ./google_test/upstream_test/run_e2e_tailorbird_with_kind_cluster.sh
- name: gke-advanced-datapath-presubmit-upstream-connectivity
  cluster: anthos-networking-ci-us-west1-b
  trigger: /test upstream-connectivity$
  rerun_command: /test upstream-connectivity
  always_run: true
  skip_fetch_head: true
  decorate: true
  decoration_config:
    gcs_configuration:
      bucket: "anthos-networking-ci"
      path_strategy: "explicit"
    timeout: 240m
  labels:
    preset-cookie-file: "true"
    preset-cookie-file-env: "true"
    preset-dind-enabled: "true"
    prow.k8s.io/pubsub.project: "anthos-networking-ci"
    prow.k8s.io/pubsub.topic: "prow-etl-trigger"
    prow.k8s.io/pubsub.runID: "prow-etl-presubmit-tests"
  path_alias: gke-internal.googlesource.com/third_party/cilium
  spec:
    containers:
    - image: gcr.io/tailorbird/kubetest2-tailorbird@sha256:dd6edb7b068410208ae185e780bfef1629ea5e07ce566c17132edb1070a71d0d
      securityContext:
        # needed for docker-in-docker
        privileged: true
      env:
      - name: GCP_PROJECT
        value: anthos-networking-ci
      - name: TEST_TYPE
        value: connectivity
      command:
      - runner.sh
      args:
      - ./google_test/upstream_test/run_e2e_tailorbird_with_kind_cluster.sh
