apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: vars
  literals:
  # REGISTRY: image registry hosting container images.
  - REGISTRY=gcr.io/anthos-baremetal-staging
  # CILIUM_CLUSTER_Name: Optional, unique cluster name used for cilium clustermesh
  # As a cilium limitation, it cannot be "default" when cluster-id is not empty.
  - CILIUM_CLUSTER_NAME=default-cluster
  # CILIUM_CLUSTER_ID: Optional, unique integer 0-255 used for cilium clustermesh.
  - CILIUM_CLUSTER_ID=100
  # CLUSTER_CIDR: Cluster wide CIDR to be used and divided into per-node /24 CIDRs.
  - CLUSTER_CIDR=192.168.0.0/16
  - SERVICE_IPV4_CIDR=10.96.0.0/20
  - CLUSTER_DNS_IP=10.96.0.10
  - TUNNEL=geneve
  # NATIVE_ROUTING: whether to enable native routing. TUNNEL should be "disabled" when
  # NATIVE_ROUTING is set to true.
  - NATIVE_ROUTING=false
  - CNI_KP_REPLACE=partial
  - CNI_KP_HEALTHZ_ADDR=""
  - CNI_KP_RETRY_HEALTHZ_BINDING=false
  - ENABLE_SOCK_LB=false
  - K8S_API_ENDPOINT=
  # ENABLE_IPV6: whether to enable IPV6.
  - ENABLE_IPV6=false
  - CNI_EXCLUSIVE=true
  - ENABLE_IPV4_MASQUERADE=true
  - ENABLE_BPF_MASQUERADE=true
  - ENABLE_EGRESS_GATEWAY=true
  - ENABLE_MCC=true
  # ENABLE_FLAT_IPV4: whether to enable Flat mode for IPv4.
  # When ENABLE_FLAT_IPV4 is set to true:
  # ENABLE_BPF_MASQUERADE, ENABLE_IPV4_MASQUERADE and ENABLE_MCC
  # must be set to false.
  # TUNNEL should be "disabled".
  - ENABLE_FLAT_IPV4=false
  - ALLOW_DISABLE_SOURCE_IP_VALIDATION=false
  - ENABLE_GNG=false
  - AUTO_DIRECT_NODE_ROUTES_IPV4=false
  - AUTO_DIRECT_NODE_ROUTES_IPV6=false
  - ENABLE_DPV2MULTINIC=true
  - DPV2LBMODE=snat
  - CILIUM_TAG=v1.13.7-anthos1.28-gke.10

resources:
- anet.yaml
- configmap.yaml
- operator.yaml
- role.yaml
- rolebind.yaml
- serviceaccount.yaml
- networklogging.yaml
- networklogging-crd.yaml
- networking.gke.io_trafficsteerings.yaml
- networking.gke.io_networks.yaml
- networking.gke.io_networkinterfaces.yaml
- default_pod_network.yaml

vars:
- name: CILIUM_CLUSTER_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
  fieldref:
    fieldpath: data.CILIUM_CLUSTER_NAME
- name: ENABLE_DPV2MULTINIC
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
  fieldref:
    fieldpath: data.ENABLE_DPV2MULTINIC
- name: CILIUM_CLUSTER_ID
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
  fieldref:
    fieldpath: data.CILIUM_CLUSTER_ID
- name: CLUSTER_CIDR
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
  fieldref:
    fieldpath: data.CLUSTER_CIDR
- name: SERVICE_IPV4_CIDR
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
  fieldref:
    fieldpath: data.SERVICE_IPV4_CIDR
- name: CLUSTER_DNS_IP
  objref:
    kind: ConfigMap
    name: vars
    apiVersion: v1
  fieldref:
    fieldpath: data.CLUSTER_DNS_IP
- name: TUNNEL
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.TUNNEL
- name: NATIVE_ROUTING
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.NATIVE_ROUTING
- name: ENABLE_IPV6
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.ENABLE_IPV6
- name: REGISTRY
  fieldref:
    fieldPath: data.REGISTRY
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
- name: CNI_KP_REPLACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
  fieldref:
    fieldPath: data.CNI_KP_REPLACE
- name: CNI_KP_HEALTHZ_ADDR
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
  fieldref:
    fieldPath: data.CNI_KP_HEALTHZ_ADDR
- name: CNI_KP_RETRY_HEALTHZ_BINDING
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
  fieldref:
    fieldPath: data.CNI_KP_RETRY_HEALTHZ_BINDING
- name: ENABLE_SOCK_LB
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
  fieldref:
    fieldPath: data.ENABLE_SOCK_LB
- name: K8S_API_ENDPOINT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
  fieldref:
    fieldpath: data.K8S_API_ENDPOINT
- name: CNI_EXCLUSIVE
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.CNI_EXCLUSIVE
- name: ENABLE_IPV4_MASQUERADE
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.ENABLE_IPV4_MASQUERADE
- name: ENABLE_BPF_MASQUERADE
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.ENABLE_BPF_MASQUERADE
- name: ENABLE_EGRESS_GATEWAY
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.ENABLE_EGRESS_GATEWAY
- name: ENABLE_MCC
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.ENABLE_MCC
- name: ENABLE_FLAT_IPV4
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.ENABLE_FLAT_IPV4
- name: ALLOW_DISABLE_SOURCE_IP_VALIDATION
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.ALLOW_DISABLE_SOURCE_IP_VALIDATION
- name: ENABLE_GNG
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.ENABLE_GNG
- name: AUTO_DIRECT_NODE_ROUTES_IPV4
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.AUTO_DIRECT_NODE_ROUTES_IPV4
- name: AUTO_DIRECT_NODE_ROUTES_IPV6
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.AUTO_DIRECT_NODE_ROUTES_IPV6
- name: DPV2LBMODE
  objref:
    kind: ConfigMap
    version: v1
    name: vars
  fieldref:
    fieldpath: data.DPV2LBMODE
- name: CILIUM_TAG
  fieldref:
    fieldPath: data.CILIUM_TAG
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
configurations:
- params.yaml
