apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkloggings.networking.gke.io
spec:
  group: networking.gke.io
  names:
    kind: NetworkLogging
    singular: networklogging
    plural: networkloggings
    shortNames:
    - nl
  scope: Cluster
  preserveUnknownFields: false
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: NetworkLogging describes the specification used by network logging.
        type: object
        properties:
          metadata:
            type: object
            properties:
              name:
                type: string
                pattern: "^default$"
          spec:
            description: Spec is the desired configuration for network logging.
            type: object
            properties:
              cluster:
                description: Cluster specifies the log options for cluster-level network logging.
                type: object
                properties:
                  allow:
                    description: Allow specifies the log action for policy-allowed connections.
                    type: object
                    properties:
                      log:
                        description: Log specifies if logging is enabled or not. The default value is false.
                        type: boolean
                      delegate:
                        description: Delegate can only be true if Log is true. Log:false, Delegate:true is invalid.
                          If Delegate is true, logging will be controlled by the annotation of matching network policies.
                        type: boolean
                  deny:
                    description: Deny specifies the log action for policy-denied connections.
                    type: object
                    properties:
                      log:
                        description: Log specifies if logging is enabled or not. The default value is false.
                        type: boolean
                      delegate:
                        description: Delegate can only be true if Log is true. Log:false, Delegate:true is invalid.
                          If Delegate is true, logging will be controlled by the annotation of the pod's namespace.
                        type: boolean
