varReference:
- path: data/cluster-name
  kind: ConfigMap
- path: data/cluster-id
  kind: ConfigMap
- path: data/ipv4-native-routing-cidr
  kind: ConfigMap
- path: data/tunnel
  kind: ConfigMap
- path: data/enable-endpoint-routes
  kind: ConfigMap
- path: data/auto-direct-node-routes
  kind: ConfigMap
- path: data/kube-proxy-replacement
  kind: ConfigMap
- path: data/k8s-api-server
  kind: ConfigMap
- path: data/enable-ipv6
  kind: ConfigMap
- path: data/enable-ipv6-ndp
  kind: ConfigMap
- path: spec/template/spec/containers/image
  kind: DaemonSet
- path: spec/template/spec/initContainers/image
  kind: DaemonSet
- path: spec/template/metadata/annotations
  kind: DaemonSet
- path: spec/template/spec/containers/image
  kind: Deployment
- path: spec/routes/to
  kind: Network
- path: spec/dnsConfig/nameservers
  kind: Network
- path: data/enable-google-multi-nic
  kind: ConfigMap
- path: spec/template/spec/containers/lifecycle/postStart/exec/command
  kind: DaemonSet
- path: data/enable-ipv4-masquerade
  kind: ConfigMap
- path: data/enable-bpf-masquerade
  kind: ConfigMap
- path: data/enable-ipv4-egress-gateway
  kind: ConfigMap
- path: data/enable-traffic-steering
  kind: ConfigMap
- path: data/enable-flat-ipv4
  kind: ConfigMap
- path: data/allow-disable-source-ip-validation
  kind: ConfigMap
- path: data/enable-gng
  kind: ConfigMap
- path: data/auto-direct-node-routes-ipv4
  kind: ConfigMap
- path: data/auto-direct-node-routes-ipv6
  kind: ConfigMap
- path: data/kube-proxy-replacement-healthz-bind-address
  kind: ConfigMap
- path: data/retry-kube-proxy-healthz-binding
  kind: ConfigMap
- path: data/enable-host-reachable-services
  kind: ConfigMap
- path: data/bpf-lb-sock
  kind: ConfigMap
- path: data/bpf-lb-sock-hostns-only
  kind: ConfigMap
- path: data/bpf-lb-mode
  kind: ConfigMap
- path: spec/template/spec/containers/image
  kind: DaemonSet
- path: spec/template/spec/initContainers/image
  kind: DaemonSet
- path: spec/template/spec/containers/image
  kind: Deployment
