/*
Copyright 2021 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	trafficsteeringv1alpha1 "github.com/cilium/cilium/pkg/gke/apis/trafficsteering/v1alpha1"
	versioned "github.com/cilium/cilium/pkg/gke/client/trafficsteering/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/gke/client/trafficsteering/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/cilium/cilium/pkg/gke/client/trafficsteering/listers/trafficsteering/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TrafficSteeringInformer provides access to a shared informer and lister for
// TrafficSteerings.
type TrafficSteeringInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TrafficSteeringLister
}

type trafficSteeringInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTrafficSteeringInformer constructs a new informer for TrafficSteering type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTrafficSteeringInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTrafficSteeringInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTrafficSteeringInformer constructs a new informer for TrafficSteering type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTrafficSteeringInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1alpha1().TrafficSteerings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1alpha1().TrafficSteerings(namespace).Watch(context.TODO(), options)
			},
		},
		&trafficsteeringv1alpha1.TrafficSteering{},
		resyncPeriod,
		indexers,
	)
}

func (f *trafficSteeringInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTrafficSteeringInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *trafficSteeringInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&trafficsteeringv1alpha1.TrafficSteering{}, f.defaultInformer)
}

func (f *trafficSteeringInformer) Lister() v1alpha1.TrafficSteeringLister {
	return v1alpha1.NewTrafficSteeringLister(f.Informer().GetIndexer())
}
