FROM golang:1.18 as anet-build

WORKDIR /cilium

COPY pkg /cilium/pkg
COPY api /cilium/api
COPY slim-daemon /cilium/slim-daemon
COPY go.mod /cilium/go.mod
COPY go.sum /cilium/go.sum
COPY vendor /cilium/vendor

RUN make -C /cilium/slim-daemon linux

FROM ubuntu

COPY --from=anet-build /cilium/slim-daemon/anet-agent /

