# The overwrite-patch stores the configurations that are different from the GDC-AG production environment.
apiVersion: v1
data:
  # Disable hubble to reduce log noise as we don't need to export the flow logs.
  enable-hubble: "false"
  # TODO(b/403341253): remove the configuration once it's updated in GDC-AG repo.
  kube-proxy-replacement: "false"
  google-multi-nic-host-mapping: "128=mgmt-network,129=blue-network,130=green-network"
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
