apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  name: gke-advanced-datapath-k8s-conformance-test-rookery
  namespace: tailorbird-users
spec:
  ttlSeconds: 7200 # 2 hrs
  knests:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Knest
    metadata:
      name: gke-advanced-datapath-k8s-conformance-test-knest
    spec:
      clusters:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          name: gke-anthos-datapath-kind-cluster
          namespace: tailorbird-users
        spec:
          provider: gcp
          distribution: kind
          provisionerArgs:
            machineType: n2-standard-16
            systemImage: ubuntu-os-pro-cloud/ubuntu-minimal-pro-2004-lts
            dockerVersion: 5:24.0.4-1~ubuntu.20.04~focal
            numNodes: "3"
            version: v0.24.0 # This is used because google:cilium v1.15 is released to GKE 1.31, we need kind v0.24.0 to support node image with v1.31
            username: prowuser
            transport: proxy
            gcpOptionsProject: anthos-networking-ci
