/*
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/gke/apis/flowtrace/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFlowTraces implements FlowTraceInterface
type FakeFlowTraces struct {
	Fake *FakeNetworkingV1alpha1
}

var flowtracesResource = v1alpha1.SchemeGroupVersion.WithResource("flowtraces")

var flowtracesKind = v1alpha1.SchemeGroupVersion.WithKind("FlowTrace")

// Get takes name of the flowTrace, and returns the corresponding flowTrace object, and an error if there is any.
func (c *FakeFlowTraces) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FlowTrace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(flowtracesResource, name), &v1alpha1.FlowTrace{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FlowTrace), err
}

// List takes label and field selectors, and returns the list of FlowTraces that match those selectors.
func (c *FakeFlowTraces) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FlowTraceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(flowtracesResource, flowtracesKind, opts), &v1alpha1.FlowTraceList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FlowTraceList{ListMeta: obj.(*v1alpha1.FlowTraceList).ListMeta}
	for _, item := range obj.(*v1alpha1.FlowTraceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested flowTraces.
func (c *FakeFlowTraces) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(flowtracesResource, opts))
}

// Create takes the representation of a flowTrace and creates it.  Returns the server's representation of the flowTrace, and an error, if there is any.
func (c *FakeFlowTraces) Create(ctx context.Context, flowTrace *v1alpha1.FlowTrace, opts v1.CreateOptions) (result *v1alpha1.FlowTrace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(flowtracesResource, flowTrace), &v1alpha1.FlowTrace{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FlowTrace), err
}

// Update takes the representation of a flowTrace and updates it. Returns the server's representation of the flowTrace, and an error, if there is any.
func (c *FakeFlowTraces) Update(ctx context.Context, flowTrace *v1alpha1.FlowTrace, opts v1.UpdateOptions) (result *v1alpha1.FlowTrace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(flowtracesResource, flowTrace), &v1alpha1.FlowTrace{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FlowTrace), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFlowTraces) UpdateStatus(ctx context.Context, flowTrace *v1alpha1.FlowTrace, opts v1.UpdateOptions) (*v1alpha1.FlowTrace, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(flowtracesResource, "status", flowTrace), &v1alpha1.FlowTrace{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FlowTrace), err
}

// Delete takes name of the flowTrace and deletes it. Returns an error if one occurs.
func (c *FakeFlowTraces) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(flowtracesResource, name, opts), &v1alpha1.FlowTrace{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFlowTraces) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(flowtracesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FlowTraceList{})
	return err
}

// Patch applies the patch and returns the patched flowTrace.
func (c *FakeFlowTraces) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FlowTrace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(flowtracesResource, name, pt, data, subresources...), &v1alpha1.FlowTrace{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FlowTrace), err
}
