/*
Copyright 2023 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/gke/apis/remotenode/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRemoteNodes implements RemoteNodeInterface
type FakeRemoteNodes struct {
	Fake *FakeNetworkingV1alpha1
	ns   string
}

var remotenodesResource = schema.GroupVersionResource{Group: "networking.gke.io", Version: "v1alpha1", Resource: "remotenodes"}

var remotenodesKind = schema.GroupVersionKind{Group: "networking.gke.io", Version: "v1alpha1", Kind: "RemoteNode"}

// Get takes name of the remoteNode, and returns the corresponding remoteNode object, and an error if there is any.
func (c *FakeRemoteNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RemoteNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(remotenodesResource, c.ns, name), &v1alpha1.RemoteNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RemoteNode), err
}

// List takes label and field selectors, and returns the list of RemoteNodes that match those selectors.
func (c *FakeRemoteNodes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RemoteNodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(remotenodesResource, remotenodesKind, c.ns, opts), &v1alpha1.RemoteNodeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RemoteNodeList{ListMeta: obj.(*v1alpha1.RemoteNodeList).ListMeta}
	for _, item := range obj.(*v1alpha1.RemoteNodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested remoteNodes.
func (c *FakeRemoteNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(remotenodesResource, c.ns, opts))

}

// Create takes the representation of a remoteNode and creates it.  Returns the server's representation of the remoteNode, and an error, if there is any.
func (c *FakeRemoteNodes) Create(ctx context.Context, remoteNode *v1alpha1.RemoteNode, opts v1.CreateOptions) (result *v1alpha1.RemoteNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(remotenodesResource, c.ns, remoteNode), &v1alpha1.RemoteNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RemoteNode), err
}

// Update takes the representation of a remoteNode and updates it. Returns the server's representation of the remoteNode, and an error, if there is any.
func (c *FakeRemoteNodes) Update(ctx context.Context, remoteNode *v1alpha1.RemoteNode, opts v1.UpdateOptions) (result *v1alpha1.RemoteNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(remotenodesResource, c.ns, remoteNode), &v1alpha1.RemoteNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RemoteNode), err
}

// Delete takes name of the remoteNode and deletes it. Returns an error if one occurs.
func (c *FakeRemoteNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(remotenodesResource, c.ns, name, opts), &v1alpha1.RemoteNode{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRemoteNodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(remotenodesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RemoteNodeList{})
	return err
}

// Patch applies the patch and returns the patched remoteNode.
func (c *FakeRemoteNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RemoteNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(remotenodesResource, c.ns, name, pt, data, subresources...), &v1alpha1.RemoteNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RemoteNode), err
}
