//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by deepcopy-gen. DO NOT EDIT.

package sfc

import (
	bpf "github.com/cilium/cilium/pkg/bpf"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CIDREntry) DeepCopyInto(out *CIDREntry) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CIDREntry.
func (in *CIDREntry) DeepCopy() *CIDREntry {
	if in == nil {
		return nil
	}
	out := new(CIDREntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapValue is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapValue.
func (in *CIDREntry) DeepCopyMapValue() bpf.MapValue {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CIDRKey) DeepCopyInto(out *CIDRKey) {
	*out = *in
	in.CIDR.DeepCopyInto(&out.CIDR)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CIDRKey.
func (in *CIDRKey) DeepCopy() *CIDRKey {
	if in == nil {
		return nil
	}
	out := new(CIDRKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapKey is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapKey.
func (in *CIDRKey) DeepCopyMapKey() bpf.MapKey {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowEntry4) DeepCopyInto(out *FlowEntry4) {
	*out = *in
	in.PreviousHopAddress.DeepCopyInto(&out.PreviousHopAddress)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowEntry4.
func (in *FlowEntry4) DeepCopy() *FlowEntry4 {
	if in == nil {
		return nil
	}
	out := new(FlowEntry4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapValue is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapValue.
func (in *FlowEntry4) DeepCopyMapValue() bpf.MapValue {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowKey4) DeepCopyInto(out *FlowKey4) {
	*out = *in
	in.SourceAddr.DeepCopyInto(&out.SourceAddr)
	in.DestAddr.DeepCopyInto(&out.DestAddr)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowKey4.
func (in *FlowKey4) DeepCopy() *FlowKey4 {
	if in == nil {
		return nil
	}
	out := new(FlowKey4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapKey is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapKey.
func (in *FlowKey4) DeepCopyMapKey() bpf.MapKey {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathEntry) DeepCopyInto(out *PathEntry) {
	*out = *in
	in.Address.DeepCopyInto(&out.Address)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathEntry.
func (in *PathEntry) DeepCopy() *PathEntry {
	if in == nil {
		return nil
	}
	out := new(PathEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapValue is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapValue.
func (in *PathEntry) DeepCopyMapValue() bpf.MapValue {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathKey) DeepCopyInto(out *PathKey) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathKey.
func (in *PathKey) DeepCopy() *PathKey {
	if in == nil {
		return nil
	}
	out := new(PathKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapKey is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapKey.
func (in *PathKey) DeepCopyMapKey() bpf.MapKey {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyMapValue is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapValue.
func (in *PathKey) DeepCopyMapValue() bpf.MapValue {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectKey) DeepCopyInto(out *SelectKey) {
	*out = *in
	in.SrcCIDR.DeepCopyInto(&out.SrcCIDR)
	in.DstCIDR.DeepCopyInto(&out.DstCIDR)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectKey.
func (in *SelectKey) DeepCopy() *SelectKey {
	if in == nil {
		return nil
	}
	out := new(SelectKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapKey is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapKey.
func (in *SelectKey) DeepCopyMapKey() bpf.MapKey {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
