apiVersion: v1
data:
  # Enabling ipv4 masquerading to support GKE connect connection.
  # GKE connect is required for tailorbird to bring up the cluster,
  # when ABM cluster not in private mode.
  enable-ipv4-masquerade: "true"
  # Disable k8s-interface-only to support GKE connect connection.
  # GKE connect is required for tailorbird to bring up the cluster,
  # when ABM cluster not in private mode.
  k8s-interface-only: "false"
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
