//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	networkv1 "github.com/GoogleCloudPlatform/gke-networking-api/apis/network/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	apicorev1 "kubevirt.io/api/core/v1"
	"kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessManagementConfig) DeepCopyInto(out *AccessManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessManagementConfig.
func (in *AccessManagementConfig) DeepCopy() *AccessManagementConfig {
	if in == nil {
		return nil
	}
	out := new(AccessManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessManagementData) DeepCopyInto(out *AccessManagementData) {
	*out = *in
	if in.AccessRequests != nil {
		in, out := &in.AccessRequests, &out.AccessRequests
		*out = make([]AccessRequest, len(*in))
		copy(*out, *in)
	}
	if in.PasswordResetRequests != nil {
		in, out := &in.PasswordResetRequests, &out.PasswordResetRequests
		*out = make([]PasswordResetRequest, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessManagementData.
func (in *AccessManagementData) DeepCopy() *AccessManagementData {
	if in == nil {
		return nil
	}
	out := new(AccessManagementData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessManagementStatus) DeepCopyInto(out *AccessManagementStatus) {
	*out = *in
	if in.AccessRequests != nil {
		in, out := &in.AccessRequests, &out.AccessRequests
		*out = make([]AccessRequestStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PasswordResetRequests != nil {
		in, out := &in.PasswordResetRequests, &out.PasswordResetRequests
		*out = make([]PasswordResetRequestStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessManagementStatus.
func (in *AccessManagementStatus) DeepCopy() *AccessManagementStatus {
	if in == nil {
		return nil
	}
	out := new(AccessManagementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessRequest) DeepCopyInto(out *AccessRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessRequest.
func (in *AccessRequest) DeepCopy() *AccessRequest {
	if in == nil {
		return nil
	}
	out := new(AccessRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessRequestStatus) DeepCopyInto(out *AccessRequestStatus) {
	*out = *in
	if in.VirtualMachineAccessRequestStatus != nil {
		in, out := &in.VirtualMachineAccessRequestStatus, &out.VirtualMachineAccessRequestStatus
		*out = new(VirtualMachineAccessRequestStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessRequestStatus.
func (in *AccessRequestStatus) DeepCopy() *AccessRequestStatus {
	if in == nil {
		return nil
	}
	out := new(AccessRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedCompute) DeepCopyInto(out *AdvancedCompute) {
	*out = *in
	if in.DedicatedCPUPlacement != nil {
		in, out := &in.DedicatedCPUPlacement, &out.DedicatedCPUPlacement
		*out = new(bool)
		**out = **in
	}
	if in.IsolatedEmulatorThread != nil {
		in, out := &in.IsolatedEmulatorThread, &out.IsolatedEmulatorThread
		*out = new(bool)
		**out = **in
	}
	if in.HugePageSize != nil {
		in, out := &in.HugePageSize, &out.HugePageSize
		*out = new(HugePageSize)
		**out = **in
	}
	if in.NUMAGuestMappingPassthrough != nil {
		in, out := &in.NUMAGuestMappingPassthrough, &out.NUMAGuestMappingPassthrough
		*out = new(NUMAGuestMappingPassthrough)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedCompute.
func (in *AdvancedCompute) DeepCopy() *AdvancedCompute {
	if in == nil {
		return nil
	}
	out := new(AdvancedCompute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bootloader) DeepCopyInto(out *Bootloader) {
	*out = *in
	if in.EnableSecureBoot != nil {
		in, out := &in.EnableSecureBoot, &out.EnableSecureBoot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bootloader.
func (in *Bootloader) DeepCopy() *Bootloader {
	if in == nil {
		return nil
	}
	out := new(Bootloader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CDRom) DeepCopyInto(out *CDRom) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CDRom.
func (in *CDRom) DeepCopy() *CDRom {
	if in == nil {
		return nil
	}
	out := new(CDRom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CDRomStatus) DeepCopyInto(out *CDRomStatus) {
	*out = *in
	if in.Ejected != nil {
		in, out := &in.Ejected, &out.Ejected
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CDRomStatus.
func (in *CDRomStatus) DeepCopy() *CDRomStatus {
	if in == nil {
		return nil
	}
	out := new(CDRomStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPU) DeepCopyInto(out *CPU) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPU.
func (in *CPU) DeepCopy() *CPU {
	if in == nil {
		return nil
	}
	out := new(CPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInit) DeepCopyInto(out *CloudInit) {
	*out = *in
	if in.NoCloudSource != nil {
		in, out := &in.NoCloudSource, &out.NoCloudSource
		*out = new(apicorev1.CloudInitNoCloudSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInit.
func (in *CloudInit) DeepCopy() *CloudInit {
	if in == nil {
		return nil
	}
	out := new(CloudInit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Compute) DeepCopyInto(out *Compute) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(CPU)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(Memory)
		(*in).DeepCopyInto(*out)
	}
	if in.Guaranteed != nil {
		in, out := &in.Guaranteed, &out.Guaranteed
		*out = new(bool)
		**out = **in
	}
	if in.AdvancedCompute != nil {
		in, out := &in.AdvancedCompute, &out.AdvancedCompute
		*out = new(AdvancedCompute)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Compute.
func (in *Compute) DeepCopy() *Compute {
	if in == nil {
		return nil
	}
	out := new(Compute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataVolumeSourceDisk) DeepCopyInto(out *DataVolumeSourceDisk) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeSourceDisk.
func (in *DataVolumeSourceDisk) DeepCopy() *DataVolumeSourceDisk {
	if in == nil {
		return nil
	}
	out := new(DataVolumeSourceDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Disk) DeepCopyInto(out *Disk) {
	*out = *in
	if in.CDRom != nil {
		in, out := &in.CDRom, &out.CDRom
		*out = new(CDRom)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Disk.
func (in *Disk) DeepCopy() *Disk {
	if in == nil {
		return nil
	}
	out := new(Disk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskSource) DeepCopyInto(out *DiskSource) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(v1beta1.DataVolumeSourceHTTP)
		(*in).DeepCopyInto(*out)
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(v1beta1.DataVolumeSourceGCS)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(v1beta1.DataVolumeSourceS3)
		**out = **in
	}
	if in.Registry != nil {
		in, out := &in.Registry, &out.Registry
		*out = new(v1beta1.DataVolumeSourceRegistry)
		(*in).DeepCopyInto(*out)
	}
	if in.Disk != nil {
		in, out := &in.Disk, &out.Disk
		*out = new(DataVolumeSourceDisk)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskSource.
func (in *DiskSource) DeepCopy() *DiskSource {
	if in == nil {
		return nil
	}
	out := new(DiskSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskStatus) DeepCopyInto(out *DiskStatus) {
	*out = *in
	if in.VirtualMachineDiskName != nil {
		in, out := &in.VirtualMachineDiskName, &out.VirtualMachineDiskName
		*out = new(string)
		**out = **in
	}
	if in.CDRom != nil {
		in, out := &in.CDRom, &out.CDRom
		*out = new(CDRomStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskStatus.
func (in *DiskStatus) DeepCopy() *DiskStatus {
	if in == nil {
		return nil
	}
	out := new(DiskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Firmware) DeepCopyInto(out *Firmware) {
	*out = *in
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(types.UID)
		**out = **in
	}
	if in.Bootloader != nil {
		in, out := &in.Bootloader, &out.Bootloader
		*out = new(Bootloader)
		(*in).DeepCopyInto(*out)
	}
	if in.Serial != nil {
		in, out := &in.Serial, &out.Serial
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Firmware.
func (in *Firmware) DeepCopy() *Firmware {
	if in == nil {
		return nil
	}
	out := new(Firmware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSpec) DeepCopyInto(out *GPUSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSpec.
func (in *GPUSpec) DeepCopy() *GPUSpec {
	if in == nil {
		return nil
	}
	out := new(GPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestEnvironment) DeepCopyInto(out *GuestEnvironment) {
	*out = *in
	if in.AccessManagement != nil {
		in, out := &in.AccessManagement, &out.AccessManagement
		*out = new(AccessManagementConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestEnvironment.
func (in *GuestEnvironment) DeepCopy() *GuestEnvironment {
	if in == nil {
		return nil
	}
	out := new(GuestEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestEnvironmentData) DeepCopyInto(out *GuestEnvironmentData) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestEnvironmentData.
func (in *GuestEnvironmentData) DeepCopy() *GuestEnvironmentData {
	if in == nil {
		return nil
	}
	out := new(GuestEnvironmentData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuestEnvironmentData) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestEnvironmentDataList) DeepCopyInto(out *GuestEnvironmentDataList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GuestEnvironmentData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestEnvironmentDataList.
func (in *GuestEnvironmentDataList) DeepCopy() *GuestEnvironmentDataList {
	if in == nil {
		return nil
	}
	out := new(GuestEnvironmentDataList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuestEnvironmentDataList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestEnvironmentDataSpec) DeepCopyInto(out *GuestEnvironmentDataSpec) {
	*out = *in
	in.AccessManagement.DeepCopyInto(&out.AccessManagement)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestEnvironmentDataSpec.
func (in *GuestEnvironmentDataSpec) DeepCopy() *GuestEnvironmentDataSpec {
	if in == nil {
		return nil
	}
	out := new(GuestEnvironmentDataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestEnvironmentDataStatus) DeepCopyInto(out *GuestEnvironmentDataStatus) {
	*out = *in
	in.LastConnectTime.DeepCopyInto(&out.LastConnectTime)
	if in.AccessManagement != nil {
		in, out := &in.AccessManagement, &out.AccessManagement
		*out = new(AccessManagementStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestEnvironmentDataStatus.
func (in *GuestEnvironmentDataStatus) DeepCopy() *GuestEnvironmentDataStatus {
	if in == nil {
		return nil
	}
	out := new(GuestEnvironmentDataStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSpec) DeepCopyInto(out *InterfaceSpec) {
	*out = *in
	if in.NetworkInterfaceSpec != nil {
		in, out := &in.NetworkInterfaceSpec, &out.NetworkInterfaceSpec
		*out = new(networkv1.NetworkInterfaceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSpec.
func (in *InterfaceSpec) DeepCopy() *InterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(InterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceStatus) DeepCopyInto(out *InterfaceStatus) {
	*out = *in
	if in.NetworkInterfaceStatus != nil {
		in, out := &in.NetworkInterfaceStatus, &out.NetworkInterfaceStatus
		*out = new(networkv1.NetworkInterfaceStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceStatus.
func (in *InterfaceStatus) DeepCopy() *InterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(InterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Memory) DeepCopyInto(out *Memory) {
	*out = *in
	out.Capacity = in.Capacity.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Memory.
func (in *Memory) DeepCopy() *Memory {
	if in == nil {
		return nil
	}
	out := new(Memory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUMAGuestMappingPassthrough) DeepCopyInto(out *NUMAGuestMappingPassthrough) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUMAGuestMappingPassthrough.
func (in *NUMAGuestMappingPassthrough) DeepCopy() *NUMAGuestMappingPassthrough {
	if in == nil {
		return nil
	}
	out := new(NUMAGuestMappingPassthrough)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordResetRequest) DeepCopyInto(out *PasswordResetRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordResetRequest.
func (in *PasswordResetRequest) DeepCopy() *PasswordResetRequest {
	if in == nil {
		return nil
	}
	out := new(PasswordResetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordResetRequestStatus) DeepCopyInto(out *PasswordResetRequestStatus) {
	*out = *in
	if in.VirtualMachinePasswordResetRequestStatus != nil {
		in, out := &in.VirtualMachinePasswordResetRequestStatus, &out.VirtualMachinePasswordResetRequestStatus
		*out = new(VirtualMachinePasswordResetRequestStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordResetRequestStatus.
func (in *PasswordResetRequestStatus) DeepCopy() *PasswordResetRequestStatus {
	if in == nil {
		return nil
	}
	out := new(PasswordResetRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimInfo) DeepCopyInto(out *PersistentVolumeClaimInfo) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.VolumeMode != nil {
		in, out := &in.VolumeMode, &out.VolumeMode
		*out = new(corev1.PersistentVolumeMode)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimInfo.
func (in *PersistentVolumeClaimInfo) DeepCopy() *PersistentVolumeClaimInfo {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicKey) DeepCopyInto(out *PublicKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicKey.
func (in *PublicKey) DeepCopy() *PublicKey {
	if in == nil {
		return nil
	}
	out := new(PublicKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHSpec) DeepCopyInto(out *SSHSpec) {
	*out = *in
	out.TTL = in.TTL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHSpec.
func (in *SSHSpec) DeepCopy() *SSHSpec {
	if in == nil {
		return nil
	}
	out := new(SSHSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scheduling) DeepCopyInto(out *Scheduling) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scheduling.
func (in *Scheduling) DeepCopy() *Scheduling {
	if in == nil {
		return nil
	}
	out := new(Scheduling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupScript) DeepCopyInto(out *StartupScript) {
	*out = *in
	if in.ScriptSecretRef != nil {
		in, out := &in.ScriptSecretRef, &out.ScriptSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupScript.
func (in *StartupScript) DeepCopy() *StartupScript {
	if in == nil {
		return nil
	}
	out := new(StartupScript)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachine) DeepCopyInto(out *VirtualMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachine.
func (in *VirtualMachine) DeepCopy() *VirtualMachine {
	if in == nil {
		return nil
	}
	out := new(VirtualMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineAccessRequest) DeepCopyInto(out *VirtualMachineAccessRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineAccessRequest.
func (in *VirtualMachineAccessRequest) DeepCopy() *VirtualMachineAccessRequest {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineAccessRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineAccessRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineAccessRequestList) DeepCopyInto(out *VirtualMachineAccessRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineAccessRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineAccessRequestList.
func (in *VirtualMachineAccessRequestList) DeepCopy() *VirtualMachineAccessRequestList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineAccessRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineAccessRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineAccessRequestSpec) DeepCopyInto(out *VirtualMachineAccessRequestSpec) {
	*out = *in
	out.SSH = in.SSH
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineAccessRequestSpec.
func (in *VirtualMachineAccessRequestSpec) DeepCopy() *VirtualMachineAccessRequestSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineAccessRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineAccessRequestStatus) DeepCopyInto(out *VirtualMachineAccessRequestStatus) {
	*out = *in
	in.ProcessedAt.DeepCopyInto(&out.ProcessedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineAccessRequestStatus.
func (in *VirtualMachineAccessRequestStatus) DeepCopy() *VirtualMachineAccessRequestStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineAccessRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineAttachment) DeepCopyInto(out *VirtualMachineAttachment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineAttachment.
func (in *VirtualMachineAttachment) DeepCopy() *VirtualMachineAttachment {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDisk) DeepCopyInto(out *VirtualMachineDisk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDisk.
func (in *VirtualMachineDisk) DeepCopy() *VirtualMachineDisk {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineDisk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDiskList) DeepCopyInto(out *VirtualMachineDiskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineDisk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDiskList.
func (in *VirtualMachineDiskList) DeepCopy() *VirtualMachineDiskList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDiskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineDiskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDiskProvisionTime) DeepCopyInto(out *VirtualMachineDiskProvisionTime) {
	*out = *in
	if in.ProvisionTime != nil {
		in, out := &in.ProvisionTime, &out.ProvisionTime
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDiskProvisionTime.
func (in *VirtualMachineDiskProvisionTime) DeepCopy() *VirtualMachineDiskProvisionTime {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDiskProvisionTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDiskSpec) DeepCopyInto(out *VirtualMachineDiskSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(DiskSource)
		(*in).DeepCopyInto(*out)
	}
	out.Size = in.Size.DeepCopy()
	if in.PersistentVolumeClaimName != nil {
		in, out := &in.PersistentVolumeClaimName, &out.PersistentVolumeClaimName
		*out = new(string)
		**out = **in
	}
	if in.DiskType != nil {
		in, out := &in.DiskType, &out.DiskType
		*out = new(DiskType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDiskSpec.
func (in *VirtualMachineDiskSpec) DeepCopy() *VirtualMachineDiskSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineDiskStatus) DeepCopyInto(out *VirtualMachineDiskStatus) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProvisionTime != nil {
		in, out := &in.ProvisionTime, &out.ProvisionTime
		*out = new(VirtualMachineDiskProvisionTime)
		(*in).DeepCopyInto(*out)
	}
	if in.VirtualMachineAttachments != nil {
		in, out := &in.VirtualMachineAttachments, &out.VirtualMachineAttachments
		*out = make([]VirtualMachineAttachment, len(*in))
		copy(*out, *in)
	}
	if in.PersistentVolumeClaimInfo != nil {
		in, out := &in.PersistentVolumeClaimInfo, &out.PersistentVolumeClaimInfo
		*out = new(PersistentVolumeClaimInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineDiskStatus.
func (in *VirtualMachineDiskStatus) DeepCopy() *VirtualMachineDiskStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineDiskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineList) DeepCopyInto(out *VirtualMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineList.
func (in *VirtualMachineList) DeepCopy() *VirtualMachineList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachinePasswordResetRequest) DeepCopyInto(out *VirtualMachinePasswordResetRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachinePasswordResetRequest.
func (in *VirtualMachinePasswordResetRequest) DeepCopy() *VirtualMachinePasswordResetRequest {
	if in == nil {
		return nil
	}
	out := new(VirtualMachinePasswordResetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachinePasswordResetRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachinePasswordResetRequestList) DeepCopyInto(out *VirtualMachinePasswordResetRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachinePasswordResetRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachinePasswordResetRequestList.
func (in *VirtualMachinePasswordResetRequestList) DeepCopy() *VirtualMachinePasswordResetRequestList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachinePasswordResetRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachinePasswordResetRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachinePasswordResetRequestSpec) DeepCopyInto(out *VirtualMachinePasswordResetRequestSpec) {
	*out = *in
	out.PublicKey = in.PublicKey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachinePasswordResetRequestSpec.
func (in *VirtualMachinePasswordResetRequestSpec) DeepCopy() *VirtualMachinePasswordResetRequestSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachinePasswordResetRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachinePasswordResetRequestStatus) DeepCopyInto(out *VirtualMachinePasswordResetRequestStatus) {
	*out = *in
	in.ProcessedAt.DeepCopyInto(&out.ProcessedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachinePasswordResetRequestStatus.
func (in *VirtualMachinePasswordResetRequestStatus) DeepCopy() *VirtualMachinePasswordResetRequestStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachinePasswordResetRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineProvisionTime) DeepCopyInto(out *VirtualMachineProvisionTime) {
	*out = *in
	if in.InitProvisionTime != nil {
		in, out := &in.InitProvisionTime, &out.InitProvisionTime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.LastProvisionTime != nil {
		in, out := &in.LastProvisionTime, &out.LastProvisionTime
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineProvisionTime.
func (in *VirtualMachineProvisionTime) DeepCopy() *VirtualMachineProvisionTime {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineProvisionTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineSpec) DeepCopyInto(out *VirtualMachineSpec) {
	*out = *in
	if in.RunningState != nil {
		in, out := &in.RunningState, &out.RunningState
		*out = new(VirtualMachineRunningState)
		**out = **in
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]InterfaceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Compute.DeepCopyInto(&out.Compute)
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]Disk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Scheduling != nil {
		in, out := &in.Scheduling, &out.Scheduling
		*out = new(Scheduling)
		(*in).DeepCopyInto(*out)
	}
	if in.GuestEnvironment != nil {
		in, out := &in.GuestEnvironment, &out.GuestEnvironment
		*out = new(GuestEnvironment)
		(*in).DeepCopyInto(*out)
	}
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(GPUSpec)
		**out = **in
	}
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = new(Firmware)
		(*in).DeepCopyInto(*out)
	}
	if in.CloudInit != nil {
		in, out := &in.CloudInit, &out.CloudInit
		*out = new(CloudInit)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupScripts != nil {
		in, out := &in.StartupScripts, &out.StartupScripts
		*out = make([]StartupScript, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutoInstallGuestAgent != nil {
		in, out := &in.AutoInstallGuestAgent, &out.AutoInstallGuestAgent
		*out = new(bool)
		**out = **in
	}
	if in.UseVirtioTransitional != nil {
		in, out := &in.UseVirtioTransitional, &out.UseVirtioTransitional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineSpec.
func (in *VirtualMachineSpec) DeepCopy() *VirtualMachineSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStatus) DeepCopyInto(out *VirtualMachineStatus) {
	*out = *in
	if in.StateTransitionTime != nil {
		in, out := &in.StateTransitionTime, &out.StateTransitionTime
		*out = make(map[VirtualMachineState]metav1.Time, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ProvisionTime != nil {
		in, out := &in.ProvisionTime, &out.ProvisionTime
		*out = new(VirtualMachineProvisionTime)
		(*in).DeepCopyInto(*out)
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]InterfaceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]DiskStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStatus.
func (in *VirtualMachineStatus) DeepCopy() *VirtualMachineStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineType) DeepCopyInto(out *VirtualMachineType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineType.
func (in *VirtualMachineType) DeepCopy() *VirtualMachineType {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineType) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineTypeList) DeepCopyInto(out *VirtualMachineTypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineTypeList.
func (in *VirtualMachineTypeList) DeepCopy() *VirtualMachineTypeList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineTypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineTypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineTypeSpec) DeepCopyInto(out *VirtualMachineTypeSpec) {
	*out = *in
	out.CPU = in.CPU
	in.Memory.DeepCopyInto(&out.Memory)
	if in.Guaranteed != nil {
		in, out := &in.Guaranteed, &out.Guaranteed
		*out = new(bool)
		**out = **in
	}
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(GPUSpec)
		**out = **in
	}
	if in.AdvancedCompute != nil {
		in, out := &in.AdvancedCompute, &out.AdvancedCompute
		*out = new(AdvancedCompute)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineTypeSpec.
func (in *VirtualMachineTypeSpec) DeepCopy() *VirtualMachineTypeSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineTypeSpec)
	in.DeepCopyInto(out)
	return out
}
