/*
Copyright 2022 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/gke/apis/fqdnnetworkpolicy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// FakeFQDNNetworkPolicyLists implements FQDNNetworkPolicyListInterface
type FakeFQDNNetworkPolicyLists struct {
	Fake *FakeNetworkingV1alpha1
	ns   string
}

var fqdnnetworkpolicylistsResource = schema.GroupVersionResource{Group: "networking.gke.io", Version: "v1alpha1", Resource: "fqdnnetworkpolicylists"}

var fqdnnetworkpolicylistsKind = schema.GroupVersionKind{Group: "networking.gke.io", Version: "v1alpha1", Kind: "FQDNNetworkPolicyList"}

// Get takes name of the fQDNNetworkPolicyList, and returns the corresponding fQDNNetworkPolicyList object, and an error if there is any.
func (c *FakeFQDNNetworkPolicyLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FQDNNetworkPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(fqdnnetworkpolicylistsResource, c.ns, name), &v1alpha1.FQDNNetworkPolicyList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FQDNNetworkPolicyList), err
}
