/*
Copyright 2023 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	nodepoolv1 "github.com/cilium/cilium/pkg/gke/apis/nodepool/v1"
	scheme "github.com/cilium/cilium/pkg/gke/client/nodepool/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	rest "k8s.io/client-go/rest"
)

// NodePoolListsGetter has a method to return a NodePoolListInterface.
// A group's client should implement this interface.
type NodePoolListsGetter interface {
	NodePoolLists(namespace string) NodePoolListInterface
}

// NodePoolListInterface has methods to work with NodePoolList resources.
type NodePoolListInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*nodepoolv1.NodePoolList, error)
	NodePoolListExpansion
}

// nodePoolLists implements NodePoolListInterface
type nodePoolLists struct {
	client rest.Interface
	ns     string
}

// newNodePoolLists returns a NodePoolLists
func newNodePoolLists(c *BaremetalV1Client, namespace string) *nodePoolLists {
	return &nodePoolLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodePoolList, and returns the corresponding nodePoolList object, and an error if there is any.
func (c *nodePoolLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *nodepoolv1.NodePoolList, err error) {
	result = &nodepoolv1.NodePoolList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodepoollists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}
