apiVersion: apps/v1
kind: Deployment
metadata:
  name: anet-operator
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: cilium-operator
        resources:
          requests:
            cpu: 10m
            memory: 45Mi
