// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FlowTaggersGetter has a method to return a FlowTaggerInterface.
// A group's client should implement this interface.
type FlowTaggersGetter interface {
	FlowTaggers() FlowTaggerInterface
}

// FlowTaggerInterface has methods to work with FlowTagger resources.
type FlowTaggerInterface interface {
	Create(ctx context.Context, flowTagger *v2alpha1.FlowTagger, opts v1.CreateOptions) (*v2alpha1.FlowTagger, error)
	Update(ctx context.Context, flowTagger *v2alpha1.FlowTagger, opts v1.UpdateOptions) (*v2alpha1.FlowTagger, error)
	UpdateStatus(ctx context.Context, flowTagger *v2alpha1.FlowTagger, opts v1.UpdateOptions) (*v2alpha1.FlowTagger, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.FlowTagger, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.FlowTaggerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.FlowTagger, err error)
	FlowTaggerExpansion
}

// flowTaggers implements FlowTaggerInterface
type flowTaggers struct {
	client rest.Interface
}

// newFlowTaggers returns a FlowTaggers
func newFlowTaggers(c *CiliumV2alpha1Client) *flowTaggers {
	return &flowTaggers{
		client: c.RESTClient(),
	}
}

// Get takes name of the flowTagger, and returns the corresponding flowTagger object, and an error if there is any.
func (c *flowTaggers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.FlowTagger, err error) {
	result = &v2alpha1.FlowTagger{}
	err = c.client.Get().
		Resource("flowtaggers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FlowTaggers that match those selectors.
func (c *flowTaggers) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.FlowTaggerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.FlowTaggerList{}
	err = c.client.Get().
		Resource("flowtaggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested flowTaggers.
func (c *flowTaggers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("flowtaggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a flowTagger and creates it.  Returns the server's representation of the flowTagger, and an error, if there is any.
func (c *flowTaggers) Create(ctx context.Context, flowTagger *v2alpha1.FlowTagger, opts v1.CreateOptions) (result *v2alpha1.FlowTagger, err error) {
	result = &v2alpha1.FlowTagger{}
	err = c.client.Post().
		Resource("flowtaggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(flowTagger).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a flowTagger and updates it. Returns the server's representation of the flowTagger, and an error, if there is any.
func (c *flowTaggers) Update(ctx context.Context, flowTagger *v2alpha1.FlowTagger, opts v1.UpdateOptions) (result *v2alpha1.FlowTagger, err error) {
	result = &v2alpha1.FlowTagger{}
	err = c.client.Put().
		Resource("flowtaggers").
		Name(flowTagger.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(flowTagger).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *flowTaggers) UpdateStatus(ctx context.Context, flowTagger *v2alpha1.FlowTagger, opts v1.UpdateOptions) (result *v2alpha1.FlowTagger, err error) {
	result = &v2alpha1.FlowTagger{}
	err = c.client.Put().
		Resource("flowtaggers").
		Name(flowTagger.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(flowTagger).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the flowTagger and deletes it. Returns an error if one occurs.
func (c *flowTaggers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("flowtaggers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *flowTaggers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("flowtaggers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched flowTagger.
func (c *flowTaggers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.FlowTagger, err error) {
	result = &v2alpha1.FlowTagger{}
	err = c.client.Patch(pt).
		Resource("flowtaggers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
