//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckResult) DeepCopyInto(out *CheckResult) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckResult.
func (in *CheckResult) DeepCopy() *CheckResult {
	if in == nil {
		return nil
	}
	out := new(CheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureResult) DeepCopyInto(out *FailureResult) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]CheckResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureResult.
func (in *FailureResult) DeepCopy() *FailureResult {
	if in == nil {
		return nil
	}
	out := new(FailureResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureStatus) DeepCopyInto(out *FeatureStatus) {
	*out = *in
	if in.FailedNodeNum != nil {
		in, out := &in.FailedNodeNum, &out.FailedNodeNum
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureStatus.
func (in *FeatureStatus) DeepCopy() *FeatureStatus {
	if in == nil {
		return nil
	}
	out := new(FeatureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResult) DeepCopyInto(out *NodeResult) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]CheckResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResult.
func (in *NodeResult) DeepCopy() *NodeResult {
	if in == nil {
		return nil
	}
	out := new(NodeResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreflightCheckSummary) DeepCopyInto(out *PreflightCheckSummary) {
	*out = *in
	if in.PreflightCheckPassed != nil {
		in, out := &in.PreflightCheckPassed, &out.PreflightCheckPassed
		*out = new(bool)
		**out = **in
	}
	if in.FeatureStatuses != nil {
		in, out := &in.FeatureStatuses, &out.FeatureStatuses
		*out = make(map[string]FeatureStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreflightCheckSummary.
func (in *PreflightCheckSummary) DeepCopy() *PreflightCheckSummary {
	if in == nil {
		return nil
	}
	out := new(PreflightCheckSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRuntime) DeepCopyInto(out *VMRuntime) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRuntime.
func (in *VMRuntime) DeepCopy() *VMRuntime {
	if in == nil {
		return nil
	}
	out := new(VMRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRuntimeList) DeepCopyInto(out *VMRuntimeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMRuntime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRuntimeList.
func (in *VMRuntimeList) DeepCopy() *VMRuntimeList {
	if in == nil {
		return nil
	}
	out := new(VMRuntimeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRuntimePreflightCheck) DeepCopyInto(out *VMRuntimePreflightCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRuntimePreflightCheck.
func (in *VMRuntimePreflightCheck) DeepCopy() *VMRuntimePreflightCheck {
	if in == nil {
		return nil
	}
	out := new(VMRuntimePreflightCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMRuntimePreflightCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRuntimePreflightCheckList) DeepCopyInto(out *VMRuntimePreflightCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMRuntimePreflightCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRuntimePreflightCheckList.
func (in *VMRuntimePreflightCheckList) DeepCopy() *VMRuntimePreflightCheckList {
	if in == nil {
		return nil
	}
	out := new(VMRuntimePreflightCheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMRuntimePreflightCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRuntimePreflightCheckSpec) DeepCopyInto(out *VMRuntimePreflightCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRuntimePreflightCheckSpec.
func (in *VMRuntimePreflightCheckSpec) DeepCopy() *VMRuntimePreflightCheckSpec {
	if in == nil {
		return nil
	}
	out := new(VMRuntimePreflightCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRuntimePreflightCheckStatus) DeepCopyInto(out *VMRuntimePreflightCheckStatus) {
	*out = *in
	if in.Pass != nil {
		in, out := &in.Pass, &out.Pass
		*out = new(bool)
		**out = **in
	}
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make(map[string]NodeResult, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Failures != nil {
		in, out := &in.Failures, &out.Failures
		*out = make(map[string]FailureResult, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRuntimePreflightCheckStatus.
func (in *VMRuntimePreflightCheckStatus) DeepCopy() *VMRuntimePreflightCheckStatus {
	if in == nil {
		return nil
	}
	out := new(VMRuntimePreflightCheckStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRuntimeSpec) DeepCopyInto(out *VMRuntimeSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.UseEmulation != nil {
		in, out := &in.UseEmulation, &out.UseEmulation
		*out = new(bool)
		**out = **in
	}
	if in.VMImageFormat != nil {
		in, out := &in.VMImageFormat, &out.VMImageFormat
		*out = new(VMImageFormat)
		**out = **in
	}
	if in.EnableGPU != nil {
		in, out := &in.EnableGPU, &out.EnableGPU
		*out = new(bool)
		**out = **in
	}
	if in.InstallNvidaDriver != nil {
		in, out := &in.InstallNvidaDriver, &out.InstallNvidaDriver
		*out = new(bool)
		**out = **in
	}
	if in.CDIUploadProxyVIP != nil {
		in, out := &in.CDIUploadProxyVIP, &out.CDIUploadProxyVIP
		*out = new(string)
		**out = **in
	}
	if in.DisableCDIUploadProxyVIP != nil {
		in, out := &in.DisableCDIUploadProxyVIP, &out.DisableCDIUploadProxyVIP
		*out = new(bool)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(VMRuntimeStorage)
		**out = **in
	}
	if in.EvictionPolicy != nil {
		in, out := &in.EvictionPolicy, &out.EvictionPolicy
		*out = new(VirtualMachineEvictionPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.DeployOnNestedVirtualization != nil {
		in, out := &in.DeployOnNestedVirtualization, &out.DeployOnNestedVirtualization
		*out = new(bool)
		**out = **in
	}
	if in.AppArmorLauncherProfile != nil {
		in, out := &in.AppArmorLauncherProfile, &out.AppArmorLauncherProfile
		*out = new(string)
		**out = **in
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make(map[FeatureGateName]FeatureGateState, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRuntimeSpec.
func (in *VMRuntimeSpec) DeepCopy() *VMRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(VMRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRuntimeStatus) DeepCopyInto(out *VMRuntimeStatus) {
	*out = *in
	if in.PreflightCheckSummary != nil {
		in, out := &in.PreflightCheckSummary, &out.PreflightCheckSummary
		*out = new(PreflightCheckSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(VMRuntimeStorageStatus)
		**out = **in
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make(map[FeatureGateName]FeatureGateState, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRuntimeStatus.
func (in *VMRuntimeStatus) DeepCopy() *VMRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(VMRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRuntimeStorage) DeepCopyInto(out *VMRuntimeStorage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRuntimeStorage.
func (in *VMRuntimeStorage) DeepCopy() *VMRuntimeStorage {
	if in == nil {
		return nil
	}
	out := new(VMRuntimeStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRuntimeStorageStatus) DeepCopyInto(out *VMRuntimeStorageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRuntimeStorageStatus.
func (in *VMRuntimeStorageStatus) DeepCopy() *VMRuntimeStorageStatus {
	if in == nil {
		return nil
	}
	out := new(VMRuntimeStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineEvictionPolicy) DeepCopyInto(out *VirtualMachineEvictionPolicy) {
	*out = *in
	if in.MaxMigrationAttemptsPerVM != nil {
		in, out := &in.MaxMigrationAttemptsPerVM, &out.MaxMigrationAttemptsPerVM
		*out = new(int)
		**out = **in
	}
	if in.MigrationTargetInitializationTimeout != nil {
		in, out := &in.MigrationTargetInitializationTimeout, &out.MigrationTargetInitializationTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineEvictionPolicy.
func (in *VirtualMachineEvictionPolicy) DeepCopy() *VirtualMachineEvictionPolicy {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineEvictionPolicy)
	in.DeepCopyInto(out)
	return out
}
