// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FlowTaggerLister helps list FlowTaggers.
// All objects returned here must be treated as read-only.
type FlowTaggerLister interface {
	// List lists all FlowTaggers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.FlowTagger, err error)
	// Get retrieves the FlowTagger from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.FlowTagger, error)
	FlowTaggerListerExpansion
}

// flowTaggerLister implements the FlowTaggerLister interface.
type flowTaggerLister struct {
	indexer cache.Indexer
}

// NewFlowTaggerLister returns a new FlowTaggerLister.
func NewFlowTaggerLister(indexer cache.Indexer) FlowTaggerLister {
	return &flowTaggerLister{indexer: indexer}
}

// List lists all FlowTaggers in the indexer.
func (s *flowTaggerLister) List(selector labels.Selector) (ret []*v2alpha1.FlowTagger, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.FlowTagger))
	})
	return ret, err
}

// Get retrieves the FlowTagger from the index for a given name.
func (s *flowTaggerLister) Get(name string) (*v2alpha1.FlowTagger, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("flowtagger"), name)
	}
	return obj.(*v2alpha1.FlowTagger), nil
}
