#!/bin/bash

set -euxo pipefail
shopt -s inherit_errexit

echo
echo "==============================================================================="
echo "Starting WORA test execution"

function log_finish() {
  if [[ -n "${WORA_ARTIFACTS:-}" ]] && [[ -n "${TEST_RUN_ID:-}" ]]; then
    rm -f "${WORA_ARTIFACTS}/${TEST_RUN_ID}/junit_runner.xml"
  fi
  set +o xtrace
  echo "==============================================================================="
  echo "End of WORA test execution"
  echo
}
trap log_finish exit

set -x

# shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")"/remote_execution.sh

# Derive semi-unique id for rookery containing test application.
TEST_RUN_ID=${KUBETEST2_RUN_ID:-unset-id}

function verify_cilium_overridden {
  # assumes that KUBECONFIG is appropriately set to the SUT cluster
  local expected_cilium_image_with_tag="${1:?}"
  local pod_name
  local found_cilium_image

  resource_files=(${TAILORBIRD_RESOURCE_ENV_FILES//":"/ })
  for resource_file in "${resource_files[@]}";
  do
    # source Tailorbird resource env file to set up any proxy information.
    # this file is generated by tailorbird.
    # shellcheck disable=SC1090
    source "${resource_file}"

    # find all anetd pods
    mapfile -t anet_pod_names < <(kubectl get pods -n kube-system | grep -oP 'anetd-\w+' || true)
    if [[ -z "${anet_pod_names[*]}" ]]; then
      echo "No anetd pods found: cannot verify version." >&2
      return 0
    fi

    for pod_name in "${anet_pod_names[@]}"; do
      found_cilium_image=$(kubectl get pods "${pod_name}" -n kube-system -o yaml | yq '.spec.containers[0].image')
      if [[ "${found_cilium_image}" != "${expected_cilium_image_with_tag}" ]]; then
        echo "Cilium did not upgrade to expected version. Expected ${expected_cilium_image_with_tag}. Found ${found_cilium_image}" >&2
        return 1
      else
        echo "Cilium is successfully verified."
      fi
    done
  done
}

function enable_additional_vxlans {
  local cluster_type="${1:?}"
  local vxlan_dstport="${2:?}"
  local tool_image="us-docker.pkg.dev/anthos-networking-ci/apps/enable-additional-vxlan:latest"
  remote_execution_from_gce_bootstrapper "gcloud auth activate-service-account --key-file=bootstrapper-sa.json"
  remote_execution_from_gce_bootstrapper "gcloud auth configure-docker us-docker.pkg.dev --quiet"
  remote_execution_from_gce_bootstrapper "docker run --pull=always -v \${PWD}:/workspace '${tool_image}' enable-additional-vxlan --new-vxlan-name vxlan1 --new-vxlan-ID 43 --new-vxlan-network 10.100.0.0/21 --cluster-type '${cluster_type}' --vxlan-dstport ${vxlan_dstport}"
  remote_execution_from_gce_bootstrapper "docker run --pull=always -v \${PWD}:/workspace '${tool_image}' enable-additional-vxlan --new-vxlan-name vxlan2 --new-vxlan-ID 44 --new-vxlan-network 10.150.0.0/21 --cluster-type '${cluster_type}' --vxlan-dstport ${vxlan_dstport}"
}

function enable_http_server {
  local tool_image="us-docker.pkg.dev/anthos-networking-ci/apps/http-server:latest"
  remote_execution_from_gce_bootstrapper "gcloud auth activate-service-account --key-file=bootstrapper-sa.json"
  remote_execution_from_gce_bootstrapper "gcloud auth configure-docker us-docker.pkg.dev --quiet"
  remote_execution_from_gce_bootstrapper "docker run --pull=always -d -p 8080:8080 -v \${PWD}:/workspace '${tool_image}' http-server"
}

# Revert KUBECONFIG change made by kt2-tb, to avoid control plane login to mess
# up SUT cluster's kubeconfig.
if [[ -n "${OLD_KUBECONFIG}" ]] && [[ -n "${ARTIFACTS}" ]] && [[ "${KUBECONFIG#"${ARTIFACTS}"}" != "${KUBECONFIG}" ]]; then
  export KUBECONFIG="${OLD_KUBECONFIG-}"
fi

if [[ -n "${KUBECONFIG}" ]] && [[ -n "${CILIUM_IMAGE_WITH_TAG:-}" ]] && [[ "${DISABLE_UPGRADE_VERIFICATION}" != "true" ]]; then
  verify_cilium_overridden "${CILIUM_IMAGE_WITH_TAG}"
fi

if [[ -e "${ARTIFACTS}/.kubetest2-tailorbird/tailorbird-request.yaml" ]] && [[ -n "${ADD_VXLANS_CLUSTER_TYPE:-}" ]]; then
  enable_additional_vxlans "${ADD_VXLANS_CLUSTER_TYPE}" "${VXLAN_DSTPORT:-0}"
fi

# Start http server in bootstapper
if [[ -e "${ARTIFACTS}/.kubetest2-tailorbird/tailorbird-request.yaml" ]] && [[ -n "${ADD_VXLANS_CLUSTER_TYPE:-}" ]] && [[ "${ADD_VXLANS_CLUSTER_TYPE}" == "gdc-ag" ]]; then
  enable_http_server
fi

function calculate_cluster_artifacts() {
  local -r config="${1:?}"
  local -r artifacts="${2:?}"
  local -a cluster_artifacts_subdirs=()
  local -a resolved_cluster_artifacts_subdirs=()
  # Find paths of cluster artifacts subdirectories.
  mapfile -t cluster_artifacts_subdirs < <(
    # shellcheck disable=SC2016
    yq '.spec.knests[] as $knest
    | $knest.spec.clusters[] as $cluster
    | ".tailorbird/artifacts"
    + "/knests/\($knest.metadata.name)"
    + "/clusters/\($cluster.metadata.name)"' "${config}" || true
  )
  if [[ "${#cluster_artifacts_subdirs[@]}" -eq 0 ]]; then
    echo "No clusters found in ${config}" >&2
    return 1
  fi
  # Resolve links to find absolute paths.
  for cluster_artifacts_subdir in "${cluster_artifacts_subdirs[@]}"; do
    local resolved_path
    # Check for empty knest or cluster names.
    if [[ "${cluster_artifacts_subdir}" == *//* ]]; then
      echo "Invalid cluster artifacts subdirectory: ${cluster_artifacts_subdir}" >&2
      return 1
    fi
    resolved_path=$(realpath "${artifacts}/${cluster_artifacts_subdir}")
    resolved_cluster_artifacts_subdirs+=("${resolved_path}")
  done
  printf "%s," "${resolved_cluster_artifacts_subdirs[@]}" | sed 's/,$//'
}

function calculate_cluster_refs() {
  local paths="${1:?}"
  local -a path_array=()
  local output=""
  local i=1
  # Split the input string into an array
  IFS=',' read -ra path_array <<<"${paths}"

  # Check if there is only one path
  if [[ "${#path_array[@]}" -eq 1 ]]; then
    output="oob=${path_array[0]}"
  else
    # Loop through each path and construct the output
    for path in "${path_array[@]}"; do
      output+=",oob${i}=${path}"
      i=$((i + 1))
    done
    # Remove the first comma
    output="${output:1}"
  fi
  echo "${output}"
}

CLUSTER_ARTIFACTS=$(calculate_cluster_artifacts "${TBCONFIG:?}" "${ARTIFACTS}")
CLUSTER_REFS=$(calculate_cluster_refs "${CLUSTER_ARTIFACTS}")

# Folder for nested WORA runs, to make file layout more clear.
WORA_ARTIFACTS="${ARTIFACTS}/wora"

# Upload-external-clusters name should match namePrefix in WORA yaml. Because
# test is going to have its own junit.xml, suppress kt2 junit generation.
# Status-check-interval is increased to work around incorrect calculation of
# rookery status.
ARTIFACTS="${WORA_ARTIFACTS}" \
  kubetest2-tailorbird \
  --verbose \
  --run-id="${TEST_RUN_ID}" \
  --tbenv="${TBENV:?}" \
  --tbconfig="${WORA_CONFIG:?}" \
  --upload-external-clusters="${CLUSTER_REFS}" \
  --client-polling-interval=90s \
  --up \
  --down

function check_junit_files_for_errors() {
  local junit_files
  local junit_file
  local test_suites
  local test_suite
  local errors
  local failures
  mapfile -t junit_files < <(find "${WORA_ARTIFACTS}" -name junit_\*.xml)
  for junit_file in "${junit_files[@]}"; do
    echo "Checking ${junit_file} for failures"
    readarray -t test_suites < <(grep -E '(<testsuite).*>' "${junit_file}" || true)
    for test_suite in "${test_suites[@]}"; do
      errors="$(echo "${test_suite}" | sed -n 's/.*errors="\([0-9]*\)".*/\1/p')"
      failures="$(echo "${test_suite}" | sed -n 's/.*failures="\([0-9]*\)".*/\1/p')"
      if ((${errors:-0} != 0)) || ((${failures:-0} != 0)); then
        echo "Failures found in produced ${junit_file} output. Failing workflow" >&2
        return 1
      fi
    done
  done
}

check_junit_files_for_errors
