apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  name: wora-sut-gdch-adhoc
  namespace: tailorbird-users
spec:
  ttlSeconds: 39600 # 11 hours
  knests:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Knest
    metadata:
      name: wora-sut-gdch-adhoc
      namespace: tailorbird-users
    spec:
      clusters:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          name: wora-sut-gdch-adhoc
          namespace: tailorbird-users
        spec:
          provider: gdch
          distribution: gdch-gce-adhoc
          provisionerArgs:
            pluginSpecYaml: |
              username: "${ADHOC_USERNAME}"
              adhocOperation: "rollout"
              adhocArgs:
                pool_name: "unet"
                env_template_id: "${ENV_TEMPLATE_ID}"
                test: "${GDCH_E2E_TESTS}"
                plan: "${GDCH_E2E_TEST_PLAN}"
                start_at: "${GDCH_E2E_START_AT_TEST}"
                use_stored_entities: "true"
                run_post_diagnose: "true"
                run_per_diagnose: "false"
                comment: "AN Shift left testing"
                tb_update_oc: "unet"
                tb_update_spec: "${UPDATE_SPEC_STRING}"
