apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  name: wora-sut-abm-atl
  namespace: tailorbird-users
spec:
  ttlSeconds: 86400 # 1 day
  knests:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Knest
    metadata:
      name: wora-sut-abm-atl
    spec:
      clusters:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          name: wora-sut-abm-atl
          namespace: tailorbird-users
        spec:
          distribution: gke-baremetal
          location: atl
          provider: vsphere
          provisionerArgs:
            # Exact version of ABM is required to generate addon configurations.
            bmctlVersion: 1.29.100-gke.76
            passthroughEnv: |
              {
                "MANIFEST_PROFILE_ENV": "staging",
                "CLUSTER_SIZE": "variable",
                "NUM_CONTROL": "1",
                "NUM_WORKER": "2",
                "NUM_LB": "0",
                "NUM_NETWORKS": "2",
                "PLATFORM": "vsphere",
                "LAB_ID": "atl_shared"
              }
            proxyPort: "8218"
            serverOS: ubuntu2004
            username: prowuser
