apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  name: wora-sut-gdch-abm-gce
  namespace: tailorbird-users
spec:
  ttlSeconds: 14400 # 4 hours
  knests:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Knest
    metadata:
      name: wora-sut-gdch-abm-gce
    spec:
      clusters:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          name: wora-sut-gdch-abm-gce-1
          namespace: tailorbird-users
        spec:
          distribution: gke
          provider: baremetal
          provisionerArgs:
            # Exact version of ABM is required to generate addon configurations.
            bmctlVersion: 1.32.800-gke.126
            # Per yaqs/6581285177727647744 only machine type N2 is supported for
            # nested-virtualization. The nested virtualization is enabled
            # through USE_EMULATION ENV. All passthroughEnv supported can be
            # found
            # https://source.corp.google.com/h/gke-internal/syllogi/baremetal/+/master:test-infra/api/v1/config.go;drc=921bb69df401eb9da234a009af3e86c0844ef0fc
            passthroughEnv: |
              {
                "MANIFEST_PROFILE_ENV": "staging",
                "CLUSTER_SIZE": "variable",
                "NUM_CONTROL": "1",
                "NUM_WORKER": "2",
                "NUM_LB": "0",
                "USE_EMULATION": "false",
                "NODE_IMAGE_SIZE": "n2-standard-4",
                "NODE_DISK_SIZE": "150",
                "PRIVATE_MODE": "true",
                "NUM_NETWORKS": "2",
                "POD_CIDR": "10.240.0.0/17",
                "SERVICE_CIDR": "172.26.0.0/19",
                "VXLANID": "42"
              }
            project: anthos-networking-ci
            proxyPort: "8222"
            username: prowuser
            serverOS: gdch-rocky
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          name: wora-sut-gdch-abm-gce-2
          namespace: tailorbird-users
        spec:
          distribution: gke
          provider: baremetal
          provisionerArgs:
            # Exact version of ABM is required to generate addon configurations.
            bmctlVersion: 1.32.800-gke.126
            # Per yaqs/6581285177727647744 only machine type N2 is supported for
            # nested-virtualization. The nested virtualization is enabled
            # through USE_EMULATION ENV. All passthroughEnv supported can be
            # found
            # https://source.corp.google.com/h/gke-internal/syllogi/baremetal/+/master:test-infra/api/v1/config.go;drc=921bb69df401eb9da234a009af3e86c0844ef0fc
            passthroughEnv: |
              {
                "MANIFEST_PROFILE_ENV": "staging",
                "CLUSTER_SIZE": "variable",
                "NUM_CONTROL": "1",
                "NUM_WORKER": "2",
                "NUM_LB": "0",
                "USE_EMULATION": "false",
                "NODE_IMAGE_SIZE": "n2-standard-4",
                "NODE_DISK_SIZE": "150",
                "PRIVATE_MODE": "true",
                "NUM_NETWORKS": "2",
                "VXLAN_NETWORK_RANGE": "10.200.64.0/21",
                "POD_CIDR": "10.241.0.0/17",
                "SERVICE_CIDR": "172.26.14.0/19",
                "VXLANID": "52"
              }
            project: anthos-networking-ci
            proxyPort: "8223"
            username: prowuser
            serverOS: gdch-rocky
  applications:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Application
    metadata:
      name: k8s-net-post-provisioner-rookery
      namespace: tailorbird-users
    spec:
      resourceTypeReference:
        name: k8s-net-post-provisioner
        version: latest
        controlPlane: gcp
      directives:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: ExecutionDirective
        metadata:
          name: k8s-net-post-provisioner-execution
        spec:
          targets:
          - namePrefix: wora-sut-gdch-abm-gce-1
            kind: Cluster
            namespace: tailorbird-users
          - namePrefix: wora-sut-gdch-abm-gce-2
            kind: Cluster
            namespace: tailorbird-users
          env:
            POSTPROVISIONER_FEATURES: "addvxlans,multicluster,httpserver"
            ADD_VXLANS_CLUSTER_TYPE: "gdc-ag"
            CILIUM_CLUSTERMESH_IMAGE_WITH_TAG: '{{ Env "CILIUM_CLUSTERMESH_IMAGE_WITH_TAG" }}'
            HTTP_SERVER_IMAGE: "us-docker.pkg.dev/anthos-networking-ci/apps/http-server:latest"
            HTTP_SERVER_PORT: "8080"
