apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  name: wora-sut-abm-gce
  namespace: tailorbird-users
spec:
  ttlSeconds: 86400 # 1 day
  knests:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Knest
    metadata:
      name: wora-sut-abm-gce
    spec:
      clusters:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          name: wora-sut-abm-gce
          namespace: tailorbird-users
        spec:
          distribution: gke
          provider: baremetal
          provisionerArgs:
            # Exact version of ABM is required to generate addon configurations.
            bmctlVersion: 1.32.800-gke.126
            # See
            # https://source.corp.google.com/h/gke-internal/codesearch/+/master:syllogi-baremetal/test-infra/README.md;drc=afe783bc4145ba18892210a10ea6dcb3e28ee389
            # for cluster size descriptions.
            passthroughEnv: |
              {
                "MANIFEST_PROFILE_ENV": "staging",
                "CLUSTER_SIZE": "conformant_cluster",
                "NUM_NETWORKS": "2",
                "USE_EMULATION": "false",
                "NODE_IMAGE_SIZE": "n2-standard-4"
              }
            project: anthos-networking-ci
            proxyPort: "8222"
            username: prowuser
  applications:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Application
    metadata:
      name: k8s-net-post-provisioner-rookery
      namespace: tailorbird-users
    spec:
      resourceTypeReference:
        name: k8s-net-post-provisioner
        version: latest
        controlPlane: gcp
      directives:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: ExecutionDirective
        metadata:
          name: k8s-net-post-provisioner-execution
        spec:
          targets:
          - namePrefix: wora-sut-abm-gce
            kind: Cluster
            namespace: tailorbird-users
          env:
            POSTPROVISIONER_FEATURES: "addvxlans"
            ADD_VXLANS_CLUSTER_TYPE: "gdc-so"
