apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  name: wora-sut-gdch-adhoc
  namespace: tailorbird-users
spec:
  ttlSeconds: 18000 # 5 hours
  knests:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Knest
    metadata:
      name: wora-sut-gdch-adhoc
      namespace: tailorbird-users
    spec:
      clusters:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          name: wora-sut-gdch-adhoc
          namespace: tailorbird-users
        spec:
          provider: gdch
          distribution: gdch-gce-adhoc
          provisionerArgs:
            pluginSpecYaml: |
              username: "ci-abm-gdch"
              adhocOperation: "rollout"
              adhocArgs:
                pool_name: "unet"
                env_template_id: "${ENV_TEMPLATE_ID}"
                test:      "TestConnectivityMultiTenant|TestClusterMeshConnectivityMultiTenant|TestClusterMeshConnectivityNewFrameworkMultiTenant|TestVMNetworkToPodIntraProjectV2MT|TestFabricTracingMultiTenant|TestILBServiceConnectivityMultiTenant|TestProjectNetworkPolicyEnforcementMultiTenant|TestEgressNATMultiTenant|TestClusterMeshHealthMultiTenant"
                plan:      "silver/unet/gce-mt"
                comment:   "AN Shift left testing"
                tb_update_oc: "unet"
                tb_update_spec: "${UPDATE_SPEC_STRING}"
