/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/gke/networkpolicylogging/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkPolicyLoggings implements NetworkPolicyLoggingInterface
type FakeNetworkPolicyLoggings struct {
	Fake *FakeNetworkingV1alpha1
	ns   string
}

var networkpolicyloggingsResource = schema.GroupVersionResource{Group: "networking.gke.io", Version: "v1alpha1", Resource: "networkpolicyloggings"}

var networkpolicyloggingsKind = schema.GroupVersionKind{Group: "networking.gke.io", Version: "v1alpha1", Kind: "NetworkPolicyLogging"}

// Get takes name of the networkPolicyLogging, and returns the corresponding networkPolicyLogging object, and an error if there is any.
func (c *FakeNetworkPolicyLoggings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkPolicyLogging, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(networkpolicyloggingsResource, c.ns, name), &v1alpha1.NetworkPolicyLogging{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPolicyLogging), err
}

// List takes label and field selectors, and returns the list of NetworkPolicyLoggings that match those selectors.
func (c *FakeNetworkPolicyLoggings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkPolicyLoggingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(networkpolicyloggingsResource, networkpolicyloggingsKind, c.ns, opts), &v1alpha1.NetworkPolicyLoggingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkPolicyLoggingList{ListMeta: obj.(*v1alpha1.NetworkPolicyLoggingList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkPolicyLoggingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkPolicyLoggings.
func (c *FakeNetworkPolicyLoggings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(networkpolicyloggingsResource, c.ns, opts))

}

// Create takes the representation of a networkPolicyLogging and creates it.  Returns the server's representation of the networkPolicyLogging, and an error, if there is any.
func (c *FakeNetworkPolicyLoggings) Create(ctx context.Context, networkPolicyLogging *v1alpha1.NetworkPolicyLogging, opts v1.CreateOptions) (result *v1alpha1.NetworkPolicyLogging, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(networkpolicyloggingsResource, c.ns, networkPolicyLogging), &v1alpha1.NetworkPolicyLogging{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPolicyLogging), err
}

// Update takes the representation of a networkPolicyLogging and updates it. Returns the server's representation of the networkPolicyLogging, and an error, if there is any.
func (c *FakeNetworkPolicyLoggings) Update(ctx context.Context, networkPolicyLogging *v1alpha1.NetworkPolicyLogging, opts v1.UpdateOptions) (result *v1alpha1.NetworkPolicyLogging, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(networkpolicyloggingsResource, c.ns, networkPolicyLogging), &v1alpha1.NetworkPolicyLogging{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPolicyLogging), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkPolicyLoggings) UpdateStatus(ctx context.Context, networkPolicyLogging *v1alpha1.NetworkPolicyLogging, opts v1.UpdateOptions) (*v1alpha1.NetworkPolicyLogging, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(networkpolicyloggingsResource, "status", c.ns, networkPolicyLogging), &v1alpha1.NetworkPolicyLogging{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPolicyLogging), err
}

// Delete takes name of the networkPolicyLogging and deletes it. Returns an error if one occurs.
func (c *FakeNetworkPolicyLoggings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(networkpolicyloggingsResource, c.ns, name), &v1alpha1.NetworkPolicyLogging{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkPolicyLoggings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(networkpolicyloggingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkPolicyLoggingList{})
	return err
}

// Patch applies the patch and returns the patched networkPolicyLogging.
func (c *FakeNetworkPolicyLoggings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkPolicyLogging, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkpolicyloggingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.NetworkPolicyLogging{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPolicyLogging), err
}
