//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLogSpec) DeepCopyInto(out *ClusterLogSpec) {
	*out = *in
	out.Allow = in.Allow
	out.Deny = in.Deny
	out.Flow = in.Flow
	if in.FlowAggregationSeconds != nil {
		in, out := &in.FlowAggregationSeconds, &out.FlowAggregationSeconds
		*out = new(uint32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLogSpec.
func (in *ClusterLogSpec) DeepCopy() *ClusterLogSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterLogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogAction) DeepCopyInto(out *LogAction) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogAction.
func (in *LogAction) DeepCopy() *LogAction {
	if in == nil {
		return nil
	}
	out := new(LogAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkLogging) DeepCopyInto(out *NetworkLogging) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkLogging.
func (in *NetworkLogging) DeepCopy() *NetworkLogging {
	if in == nil {
		return nil
	}
	out := new(NetworkLogging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkLogging) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkLoggingList) DeepCopyInto(out *NetworkLoggingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkLogging, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkLoggingList.
func (in *NetworkLoggingList) DeepCopy() *NetworkLoggingList {
	if in == nil {
		return nil
	}
	out := new(NetworkLoggingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkLoggingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkLoggingSpec) DeepCopyInto(out *NetworkLoggingSpec) {
	*out = *in
	in.Cluster.DeepCopyInto(&out.Cluster)
	in.Node.DeepCopyInto(&out.Node)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkLoggingSpec.
func (in *NetworkLoggingSpec) DeepCopy() *NetworkLoggingSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkLoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeLogSpec) DeepCopyInto(out *NodeLogSpec) {
	*out = *in
	out.Allow = in.Allow
	out.Deny = in.Deny
	out.Flow = in.Flow
	if in.FlowAggregationSeconds != nil {
		in, out := &in.FlowAggregationSeconds, &out.FlowAggregationSeconds
		*out = new(uint32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeLogSpec.
func (in *NodeLogSpec) DeepCopy() *NodeLogSpec {
	if in == nil {
		return nil
	}
	out := new(NodeLogSpec)
	in.DeepCopyInto(out)
	return out
}
