/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	networkloggingv1alpha1 "github.com/cilium/cilium/pkg/gke/apis/networklogging/v1alpha1"
	versioned "github.com/cilium/cilium/pkg/gke/client/networklogging/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/gke/client/networklogging/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/cilium/cilium/pkg/gke/client/networklogging/listers/networklogging/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkLoggingInformer provides access to a shared informer and lister for
// NetworkLoggings.
type NetworkLoggingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NetworkLoggingLister
}

type networkLoggingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewNetworkLoggingInformer constructs a new informer for NetworkLogging type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNetworkLoggingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNetworkLoggingInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredNetworkLoggingInformer constructs a new informer for NetworkLogging type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNetworkLoggingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1alpha1().NetworkLoggings().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1alpha1().NetworkLoggings().Watch(context.TODO(), options)
			},
		},
		&networkloggingv1alpha1.NetworkLogging{},
		resyncPeriod,
		indexers,
	)
}

func (f *networkLoggingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNetworkLoggingInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *networkLoggingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&networkloggingv1alpha1.NetworkLogging{}, f.defaultInformer)
}

func (f *networkLoggingInformer) Lister() v1alpha1.NetworkLoggingLister {
	return v1alpha1.NewNetworkLoggingLister(f.Informer().GetIndexer())
}
