//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowConfiguration) DeepCopyInto(out *FlowConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowConfiguration.
func (in *FlowConfiguration) DeepCopy() *FlowConfiguration {
	if in == nil {
		return nil
	}
	out := new(FlowConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowEndpoint) DeepCopyInto(out *FlowEndpoint) {
	*out = *in
	out.K8sPodKey = in.K8sPodKey
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowEndpoint.
func (in *FlowEndpoint) DeepCopy() *FlowEndpoint {
	if in == nil {
		return nil
	}
	out := new(FlowEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowProfile) DeepCopyInto(out *FlowProfile) {
	*out = *in
	out.ProtocolConfig = in.ProtocolConfig
	if in.FlowConfig != nil {
		in, out := &in.FlowConfig, &out.FlowConfig
		*out = new(FlowConfiguration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowProfile.
func (in *FlowProfile) DeepCopy() *FlowProfile {
	if in == nil {
		return nil
	}
	out := new(FlowProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTrace) DeepCopyInto(out *FlowTrace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTrace.
func (in *FlowTrace) DeepCopy() *FlowTrace {
	if in == nil {
		return nil
	}
	out := new(FlowTrace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlowTrace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTraceList) DeepCopyInto(out *FlowTraceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FlowTrace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTraceList.
func (in *FlowTraceList) DeepCopy() *FlowTraceList {
	if in == nil {
		return nil
	}
	out := new(FlowTraceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlowTraceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTraceSpec) DeepCopyInto(out *FlowTraceSpec) {
	*out = *in
	out.SourceEndpoint = in.SourceEndpoint
	in.FlowProfile.DeepCopyInto(&out.FlowProfile)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTraceSpec.
func (in *FlowTraceSpec) DeepCopy() *FlowTraceSpec {
	if in == nil {
		return nil
	}
	out := new(FlowTraceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTraceStatus) DeepCopyInto(out *FlowTraceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTraceStatus.
func (in *FlowTraceStatus) DeepCopy() *FlowTraceStatus {
	if in == nil {
		return nil
	}
	out := new(FlowTraceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolConfiguration) DeepCopyInto(out *ProtocolConfiguration) {
	*out = *in
	out.TCP = in.TCP
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolConfiguration.
func (in *ProtocolConfiguration) DeepCopy() *ProtocolConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProtocolConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPConfiguration) DeepCopyInto(out *TCPConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPConfiguration.
func (in *TCPConfiguration) DeepCopy() *TCPConfiguration {
	if in == nil {
		return nil
	}
	out := new(TCPConfiguration)
	in.DeepCopyInto(out)
	return out
}
