/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	redirectservicev1alpha1 "github.com/cilium/cilium/pkg/gke/apis/redirectservice/v1alpha1"
	versioned "github.com/cilium/cilium/pkg/gke/client/redirectservice/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/gke/client/redirectservice/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/cilium/cilium/pkg/gke/client/redirectservice/listers/redirectservice/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RedirectServiceInformer provides access to a shared informer and lister for
// RedirectServices.
type RedirectServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RedirectServiceLister
}

type redirectServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRedirectServiceInformer constructs a new informer for RedirectService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRedirectServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRedirectServiceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRedirectServiceInformer constructs a new informer for RedirectService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRedirectServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1alpha1().RedirectServices(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1alpha1().RedirectServices(namespace).Watch(context.TODO(), options)
			},
		},
		&redirectservicev1alpha1.RedirectService{},
		resyncPeriod,
		indexers,
	)
}

func (f *redirectServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRedirectServiceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *redirectServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&redirectservicev1alpha1.RedirectService{}, f.defaultInformer)
}

func (f *redirectServiceInformer) Lister() v1alpha1.RedirectServiceLister {
	return v1alpha1.NewRedirectServiceLister(f.Informer().GetIndexer())
}
