apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  disable-network-policy-crd: "false"
  enable-gdc-ilb: "true"
  enable-host-firewall: "true"
  k8s-interface-only: "true"
