//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by deepcopy-gen. DO NOT EDIT.

package pip

import (
	bpf "github.com/cilium/cilium/pkg/bpf"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CIDRKey) DeepCopyInto(out *CIDRKey) {
	*out = *in
	in.CIDR.DeepCopyInto(&out.CIDR)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CIDRKey.
func (in *CIDRKey) DeepCopy() *CIDRKey {
	if in == nil {
		return nil
	}
	out := new(CIDRKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapKey is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapKey.
func (in *CIDRKey) DeepCopyMapKey() bpf.MapKey {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingEntry) DeepCopyInto(out *RoutingEntry) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingEntry.
func (in *RoutingEntry) DeepCopy() *RoutingEntry {
	if in == nil {
		return nil
	}
	out := new(RoutingEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyMapValue is an autogenerated deepcopy function, copying the receiver, creating a new bpf.MapValue.
func (in *RoutingEntry) DeepCopyMapValue() bpf.MapValue {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
